### ISSUE TITLE
linkis add doris support

### ISSUE THREAD

**Issue by 344970961** [apache/linkis#1011]
**Is your feature request related to a problem? Please describe.**
linkis engine add doris support
**Describe the solution you'd like**
implement engine interface to add doris support
**Describe alternatives you've considered**

**Additional context**

**Comment by peacewong** [comment]
+1, doris is a very good MPP database, linkis supports doris engine is a good feature

**Comment by wushengyeyouya** [comment]
+1.
@yangzhiyue It seems like that you have a plan to implement the doris EngineConn, can we discuss it in this issue?

**Comment by jackxu2011** [comment]
the medadata query see @3259

**Comment by casionone** [comment]
Without further feedback, I closed this issue. You can reopen if necessary
