### ISSUE TITLE
Linkis-Gateway can not work with DELETE request without request body

### ISSUE THREAD

**Issue by xliuqq** [apache/linkis#1015]
**Describe the bug**
Visualis dashboard can not be deleted because **Linkis-Gateway `GatewayAuthorizationFilter::filter` method can not handle DELETE request without body.**

**To Reproduce**
1. Install dss, linkis and visualis
2. Go into Visualis 
![image](https://user-images.githubusercontent.com/11942299/134299157-d56045a7-475a-4b3e-b9c1-f464824f4994.png)

3. **Create a project, and create a dashboard, then delete the dashboard**
4. **Refresh** and will see the dashboard not deleted. 

**Expected behavior**
Visualis dashboard can be deleted.

**Version**
- linkis 1.0.2
- DSS 1.0.0
- Visualis master branch

**Comment by Dlimeng** [comment]
I want to fix this issue. Please assign to me.

**Comment by QuantumXiecao** [comment]
I want to fix this issues，you can assign it to me. Many thx!
