### ISSUE TITLE
[Bug] Some fields are missing in English internationalization

### ISSUE THREAD

**Issue by casionone** [apache/linkis#1274]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

web

### What happened + What you expected to happen

Some fields are missing in English internationalization,such as 
![企业微信截图_16414683249807](https://user-images.githubusercontent.com/7869972/148376973-f4ff9bbd-0e22-4c49-8c2f-7fc2b0a3412c.png)

![企业微信截图_16414683659593](https://user-images.githubusercontent.com/7869972/148376978-404a23e6-5257-415d-b8f9-688b56a38454.png)

### Relevent platform

none

### Reproduction script

none

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by HeZean** [comment]
Hi, I'd like to work on it!

**Comment by peacewong** [comment]
> Hi, I'd like to work on it!

ok,thanks!

**Comment by geekmu9527** [comment]
Hi, I'd like to work on it!
