### ISSUE TITLE
[Bug] Front-end code style check has warning:Unexpected console statement

### ISSUE THREAD

**Issue by casionone** [apache/linkis#1275]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

web

### What happened + What you expected to happen

 Front-end code style check has warning:Unexpected console statement

![image](https://user-images.githubusercontent.com/7869972/148377814-6d872e3b-7065-4e7a-99de-9a32d4b88055.png)

### Relevent platform

none

### Reproduction script

none

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by linbin66** [comment]
you can assign it to me.
