### ISSUE TITLE
[Feature] support both scala 2.11 and 2.12 by pom profile

### ISSUE THREAD

**Issue by dddyszy** [apache/linkis#1360]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

Scala 2.11 is deprecated in spark 2.4 and spark 3 use scala 2.12.Some people compile scala 2.4 in scala 2.12.So it's necessary to provide both 2.11 and scala 2.12 option to user

### Description

support both scala 2.11 and 2.12 by pom profile

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by casionone** [comment]
close with  pr  https://github.com/apache/linkis/pull/4146
