### ISSUE TITLE
Add junit5 test code for module [linkis-common]

### ISSUE THREAD

**Issue by husofskyzy** [apache/linkis#1634]
## Add junit5 test code for module [linkis-common]
- Module: linkis-common
- Location:linkis-commons/linkis-common
- Task status:&cross;(unfinished)/ &check;(finished) 
- Test code guide:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- Test code example: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test
-------
- 模块名: linkis-common
- 代码位置:linkis-commons/linkis-common
- 任务状态:&cross;(unfinished)/ &check;(finished) 
- 单测编写指引:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- 参考样例: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test

| Task status| Class | Type| Level of Difficulty | Note|
| :------ | :------ | :------: | :------: | :------: |
| &cross; | org.apache.linkis.common.errorcode.ErrorCodeUtils | Exception | easy |  |
| &cross; | org.apache.linkis.common.errorcode.LinkisCommonsErrorCodeSummary | Enum | easy |  |
| &cross; | org.apache.linkis.common.errorcode.LinkisComputationGovernanceErrorCodeSummary | Enum | easy |  |
| &cross; | org.apache.linkis.common.errorcode.LinkisErrorCodeSummary | Enum | easy |  |
| &cross; | org.apache.linkis.common.errorcode.LinkisFrameErrorCodeSummary | Enum | easy |  |
| &cross; | org.apache.linkis.common.exception.ErrorException | Exception | easy |  |
| &cross; | org.apache.linkis.common.exception.ExceptionLevel | Enum | easy |  |
| &cross; | org.apache.linkis.common.exception.ExceptionManager | Common | easy |  |
| &cross; | org.apache.linkis.common.exception.FatalException | Exception | easy |  |
| &cross; | org.apache.linkis.common.exception.LinkisCommonErrorException | Exception | easy |  |
| &cross; | org.apache.linkis.common.exception.LinkisException | Exception | easy |  |
| &cross; | org.apache.linkis.common.exception.LinkisRetryException | Exception | easy |  |
| &cross; | org.apache.linkis.common.exception.LinkisRuntimeException | Exception | easy |  |
| &cross; | org.apache.linkis.common.exception.WarnException | Exception | easy |  |
| &cross; | org.apache.linkis.common.io.FsPath | Common | easy |  |
| &cross; | org.apache.linkis.common.utils.ByteTimeUtils | Utils | easy |  |
| &cross; | org.apache.linkis.common.utils.DESUtil | Utils | easy |  |
| &cross; | org.apache.linkis.common.collection.LoopArray | Entity | easy |  |
| &cross; | org.apache.linkis.common.conf.Configuration | Entity | easy |  |
| &cross; | org.apache.linkis.common.conf.DWCArgumentsParser | Entity | easy |  |
| &cross; | org.apache.linkis.common.log.LogUtils | Utils | easy |  |
| &cross; | org.apache.linkis.common.utils.ArrayUtils | Utils | easy |  |
| &cross; | org.apache.linkis.common.utils.ClassUtils | Utils | easy |  |
| &cross; | org.apache.linkis.common.utils.JavaLog | Utils | easy |  |
| &cross; | org.apache.linkis.common.utils.LDAPUtils | Utils | easy |  |
| &cross; | org.apache.linkis.common.utils.Logging | Utils | easy |  |
| &cross; | org.apache.linkis.common.utils.OverloadUtils | Utils | easy |  |
| &cross; | org.apache.linkis.common.utils.LogRefreshUtilsUtils | Utils | easy |  |
| &cross; | org.apache.linkis.common.utils.RSAUtils | Utils | easy |  |
| &cross; | org.apache.linkis.common.utils.ShutdownUtils | Utils | easy |  |
| &cross; | org.apache.linkis.common.utils.Utils | Utils | easy |  |
| &cross; | org.apache.linkis.common.utils.VariableUtils | Utils | easy |  |
| &cross; | org.apache.linkis.common.utils.ZipUtils | Utils | easy |  |
| &cross; | org.apache.linkis.common.ServiceInstance | Utils | easy |  |

**Comment by AbnerHung** [comment]
Hi! Can I work on this issue?

**Comment by AbnerHung** [comment]
Hi! Can I work on this issue?

**Comment by husofskyzy** [comment]
> Hi! Can I work on this issue?

yes,just follow the guide and do it ！
