### ISSUE TITLE
[Feature] use jackson to replace gson in java code

### ISSUE THREAD

**Issue by husofskyzy** [apache/linkis#1839]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

#### 2. three types of convert   
2.1 conver from object to jsonString JacksonUtils.toJson();  
```bash
{"name":"tom","address":"beijing"} 
```
2.2 conver from object to jsonString and fromat jsonString JacksonUtils.toJsonFormat();  
```bash
{
    "name": "tom",
    "address": "beijing"
} 
```
2.3 conver from jsonString to object JacksonUtils.fromJson();    

-------

#### 2. 三种转换类型
2.1 object 转 jsonString JacksonUtils.toJson();  
```bash
 {"name":"tom","address":"beijing"} 
```
2.2 object 转 jsonString 并且格式化 and fromat jsonString JacksonUtils.toJsonFormat();  
```bash
{
    "name": "tom",
    "address": "beijing"
}  
```
2.3 jsonString 转 object JacksonUtils.fromJson();  

### Description
MapTypeAdapter，ExtraFieldClassTest，ApiJsonTest类中json的使用方法比较复杂还没有修改

-------

uniformly  is not done in class  MapTypeAdapter，ExtraFieldClassTest，ApiJsonTest cause there are complex methods

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by seedscoder** [comment]
I want to solve this issue

**Comment by husofskyzy** [comment]
I have done part of the job and i want to finish it.Maybe you can find another issue to fix.



At 2022-03-31 19:41:21, "seedscoder" ***@***.***> wrote:

I want to solve this issue
