### ISSUE TITLE
[Feature][1.1.2] change main method test to junit5 test in module linkis-cs-highavailable

### ISSUE THREAD

**Issue by husofskyzy** [apache/linkis#1891]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Description

module: linkis-cs-highavailable  
![企业微信截图_16488945036545](https://user-images.githubusercontent.com/29391030/161378643-9228f67e-b0e1-4ec3-ad98-6fb4c4714f14.png)  

change main method test to junit5 test in module linkis-cs-highavailable  

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pearfl** [comment]
please assign to me

**Comment by jackxu2011** [comment]
> please assign to me

this issue has been finished.
