### ISSUE TITLE
[Feature][1.1.2] change main method test to junit5 test in module linkis-cs-listener

### ISSUE THREAD

**Issue by husofskyzy** [apache/linkis#1892]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Description

module: linkis-cs-listener  
![企业微信截图_16488946455534](https://user-images.githubusercontent.com/29391030/161378708-76395eaa-9cb9-45dc-9fed-808bfec5b063.png)  

 change main method test to junit5 test in module linkis-cs-listener

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mroccyen** [comment]
i will try my best to do it，please assign to me

**Comment by jackxu2011** [comment]
> i will try my best to do it，please assign to me

ok
