### ISSUE TITLE
[DOC] The Linkis cluster_deployment doc needs to be improved 

### ISSUE THREAD

**Issue by sargentti** [apache/linkis#2055]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

Though there is a brief debug doc, there's errors& missings. For example local environment pre-requirements, post-install verification, wrong parameter names etc. Needs to be improved.
EN:
https://github.com/apache/incubator-linkis-website/blob/master/docs/deployment/cluster_deployment.md
CN:
https://github.com/apache/incubator-linkis-website/blob/master/i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/cluster_deployment.md

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Xlight5** [comment]
[WeOpen Star]I would like to help

**Comment by luahan77m** [comment]
Hello, I 'm interested in this issue. Can I try it?
