### ISSUE TITLE
[Bug] upgrade to hive-exec 2.3.4 due to CVE 

### ISSUE THREAD

**Issue by pjfanning** [apache/linkis#2184]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-public-enhancements

### What happened + What you expected to happen

https://github.com/advisories/GHSA-rrfq-g5fq-fc9c

hive-exec is used a few places in linkis

### Relevent platform

all

### Reproduction script

n/a

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by linbin66** [comment]
This issue can be fixed by search and replace maven dependencies, please assign it to me. @peacewong
