### ISSUE TITLE
linkis suppport hbase

### ISSUE THREAD

**Issue by nyzoupu** [apache/linkis#22]
![image](https://user-images.githubusercontent.com/4697365/62025872-ee113400-b20b-11e9-95a0-e3c7a356127d.png)
大神，看到这里说Linkis 支持hbase，想请教下目前linkis支持多hbase集群的同时访问吗

**Comment by peacewong** [comment]
Thanks for your issue. Our RoadMap has already planned support for Hbase, and we hope to further implement double-read and double-write for Hbase active and standby clusters. We hope to develop it with you to implement this feature.

**Comment by nyzoupu** [comment]
I am so glad to hear from you saying that,and it is my pleasure to implement this feature of hbase together. In addition, I am also very curious to know how you implement this feature in your roadmap?

**Comment by wushengyeyouya** [comment]
Our idea is almostly this: we use a core abstract job that encapsulates a user request, and we can implement new rules. We can use this to implement a write rule for the master HBase cluster, to implement a write rule for the slave HBase cluster, and then implement a playback rule for playing back the blocking job of JobHistory. If a write rule fails to write, the rowKey is subsequently blocked from writing to the cluster and waiting for playback.
If you have a better idea, you are welcome to discuss it!

**Comment by nyzoupu** [comment]
Got it, but i am wondering to know  whether performance would be affected  when hbase client read or write through linkis, after all, it went through many steps as an extra.

**Comment by wushengyeyouya** [comment]
It does not affect the performance of the caller, but if the concurrency is too high, there may be a slight delay in writing to HBase.

**Comment by casionone** [comment]
Without further feedback, I closed this issue. You can reopen if necessary

**Comment by nyzoupu** [comment]
您好，你发送的邮件已收到，我会尽快给你联系。谢谢
