### ISSUE TITLE
Support to run the developed spark jars

### ISSUE THREAD

**Issue by wForget** [apache/linkis#223]
**Is your feature request related to a problem? Please describe.**
用户直接上传开发好的 Spark Jars 进行运行。

**Describe the solution you'd like**
当执行用户指定的 Jars 和 MainClass 时，Spark EngineManager 不通过提交 Spark Engine 启动，而是直接提交用户指定的 Jars 和 MainClass。

**Describe alternatives you've considered**
也可以实现 Shell Engine，在 DSS 上面通过封装 Shell Engine 节点实现。

**Additional context**
如何更好的管理这种 Spark 任务？
支持 spark 多版本。

---

**Is your feature request related to a problem? Please describe.**
users directly upload the developed spark jars to run.

**Describe the solution you'd like**
When the user specified jars and mainclass are executed, spark engine manager will not start by submitting spark engine, but directly submit the user specified jars and mianclass to start.

**Describe alternatives you've considered**
Of course, you can also implement shell engine, and then encapsulate the nodes in DSS.

**Additional context**
How to better manage this kind of spark task?
Support spark multi version.

**Comment by wForget** [comment]
dolphinscheduler spark node:
![dolphinscheduler spark node](https://dolphinscheduler.apache.org/img/spark_edit.png)

**Comment by wushengyeyouya** [comment]
It is a good idea, we are planning to support it in Linkis1.0.0.
Multi version of one engine is certainly a very important feature in Linkis1.0.0.
If you are interested in those features, welcome to join us.
