### ISSUE TITLE
[Bug] linkis-cs-listener pom - wrong parent relative path 

### ISSUE THREAD

**Issue by idoflax** [apache/linkis#2387]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-public-enhancements

### What happened + What you expected to happen

The pom is pointing to the wrong relative parent path, ending up in linkis-public-enhancements instead of linkis:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>linkis</artifactId>
        <groupId>org.apache.linkis</groupId>
        <version>1.1.3</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>linkis-cs-listener</artifactId>
```

should be

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>linkis</artifactId>
        <groupId>org.apache.linkis</groupId>
        <version>1.1.3</version>
        <relativePath>../../../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>linkis-cs-listener</artifactId>
```

### Relevent platform

IntelliJ, maven, macOs

### Reproduction script

build with maven/intellij

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Thank you, you can submit PR to fix it, it is recommended to submit it to the branch dev-1.2.0

**Comment by casionone** [comment]
Without further feedback, I closed this issue. You can reopen if necessary
