### ISSUE TITLE
[Bug] [Flink] Not support YarnPerJobClusterDescriptorAdapter for FlinkSQLComputationExecutor

### ISSUE THREAD

**Issue by wbmialiu** [apache/linkis#2393]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### What happened + What you expected to happen

当 linkis 有启用个人函数功能，streamis 运行oncejob sql任务时，会导致Not support YarnPerJobClusterDescriptorAdapter for FlinkSQLComputationExecutor 的异常。
![image](https://user-images.githubusercontent.com/7869972/176843901-f5e7ba72-2f05-46b1-941a-2aecaf6df77a.png)

**Comment by legend91325** [comment]
I want to fix this issues，you can assign it to me

**Comment by legend91325** [comment]
> 

why just remove this `wds.linkis.engine.connector.hooks` property ,can fix this bug ?

**Comment by QuantumXiecao** [comment]
I want to fix this issues，you can assign it to me. @jackxu2011 @casionone
