### ISSUE TITLE
[Feature][docker] All in one docker-compose and k8s deploy

### ISSUE THREAD

**Issue by StudyExchange** [apache/linkis#2671]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

All in one docker-compose and k8s deploy, contains mainly storage/computation engines(like hive, hadoop, spark and so on), linkis, mainly Ecosystem components(like DataSphereStudio, Scriptis, Schedulis, Qualitis, Streamis, Exchangis, Visualis and so on).
- docker-compose on single-machine deploy, for easily Evaluation
- k8s on cluster deply, for production env deployment

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jacktao007** [comment]
You can try using version 1.3.0 for k8s deployment
