### ISSUE TITLE
Add junit5 test code for module [linkis-engineconn-core]

### ISSUE THREAD

**Issue by ruY9527** [apache/linkis#3014]
### Add junit5 test code for module [linkis-engineconn-core]
- Module:linkis-engineconn-core
- Location:linkis-engineconn/linkis-engineconn-core
- Task status:✗(unfinished)/ ✓(finished)
- Test code guide:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- Test code example: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test
--
- 模块名: linkis-engineconn-core
- 代码位置:linkis-engineconn/linkis-engineconn-core
- 任务状态:✗(unfinished)/ ✓(finished)
- 单测编写指引:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- 参考样例: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test

| Task status| Class | Type| Level of Difficulty | Note |
| :------ | :------ | :------: | :------: | :------: |
|   ✗         |org.apache.linkis.engineconn.core.exception.EngineConnFatalException| Exception | normal |  |
|   ✗         |org.apache.linkis.engineconn.core.execution.*| Execution | normal |  |
|   ✗         |org.apache.linkis.engineconn.core.executor.ExecutorManager| Executor | normal |  |
|   ✗         |org.apache.linkis.engineconn.core.hook.*| Hook | normal |  |
|   ✗         |org.apache.linkis.engineconn.launch.EngineConnServer| Executor | normal |  |

**Comment by binbinCheng** [comment]
i want to try.
