### ISSUE TITLE
Add junit5 test code for module [engineconn-plugins/pipeline]

### ISSUE THREAD

**Issue by ruY9527** [apache/linkis#3043]
### Add junit5 test code for module [engineconn-plugins/pipeline]
- Module: linkis-engineplugin-pipeline
- Location:linkis-engineconn-plugins/linkis-engineplugin-pipeline
- Task status:✗(unfinished)/ ✓(finished)
- Test code guide:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- Test code example: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test
--
- 模块名: linkis-engineplugin-pipeline
- 代码位置:linkis-engineconn-plugins/linkis-engineplugin-pipeline
- 任务状态:✗(unfinished)/ ✓(finished)
- 单测编写指引:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- 参考样例: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test

| Task status| Class | Type| Level of Difficulty | Note |
| :------ | :------ | :------: | :------: | :------: |
|   ✗         |org.apache.linkis.manager.engineplugin.pipeline.constant.PipeLineConstant| Constant | normal |  |
|   ✗         |org.apache.linkis.manager.engineplugin.pipeline.exception.PipeLineErrorException| Exception | normal |  |
|   ✗         |org.apache.linkis.manager.engineplugin.pipeline.executor.*| executor | normal |  |
|   ✗         |org.apache.linkis.manager.engineplugin.pipeline.factory.PipelineEngineConnFactory| Factory | normal |  |

**Comment by binbinCheng** [comment]
I want to try it
