### ISSUE TITLE
Add junit5 test code for module [engineconn-plugins/presto]

### ISSUE THREAD

**Issue by ruY9527** [apache/linkis#3051]
### Add junit5 test code for module [engineconn-plugins/presto]
- Module: linkis-engineplugin-presto
- Location:linkis-engineconn-plugins/linkis-engineplugin-presto
- Task status:✗(unfinished)/ ✓(finished)
- Test code guide:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- Test code example: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test
--
- 模块名: linkis-engineplugin-presto
- 代码位置:linkis-engineconn-plugins/linkis-engineplugin-presto
- 任务状态:✗(unfinished)/ ✓(finished)
- 单测编写指引:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- 参考样例: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test

| Task status| Class | Type| Level of Difficulty | Note |
| :------ | :------ | :------: | :------: | :------: |
|   ✗         |org.apache.linkis.engineplugin.presto.builder.PrestoProcessEngineConnLaunchBuilder| Builder | normal |  |
|   ✗         |org.apache.linkis.engineplugin.presto.conf.*| conf | normal |  |
|   ✗         |org.apache.linkis.engineplugin.presto.exception.PrestoStateInvalidException| Exception | normal |  |
|   ✗         |org.apache.linkis.engineplugin.presto.executer.PrestoEngineConnExecutor| Executor | normal |  |

**Comment by binbinCheng** [comment]
I CAN

**Comment by binbinCheng** [comment]
I want to try it
