### ISSUE TITLE
[Feature][linkis-jobhistory] Linkis job list should support search by entrance instance.

### ISSUE THREAD

**Issue by Alexkun** [apache/linkis#3391]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

I cannot search tasks in a specific entrance.

### Description

Linkis job list should support search by entrance instance.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by huangKai-2323** [comment]
I will fix this bug
