### ISSUE TITLE
[Bug] status interface 500, how to solve

### ISSUE THREAD

**Issue by joefanyu** [apache/linkis#3584]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-computation-governance

### Steps to reproduce

/api/rest_j/v1/entrance/exec_id018014linkis-cg-entrancelocalhost:9104IDE_root_spark_7/status?taskID=14

提交任务生存的id带有冒号：exec_id018014linkis-cg-entrancelocalhost:9104IDE_root_spark_7，请求状态接口时报500

### Expected behavior

/api/rest_j/v1/entrance/exec_id018014linkis-cg-entrancelocalhost:9104IDE_root_spark_7/status?taskID=14

提交任务生存的id带有冒号：exec_id018014linkis-cg-entrancelocalhost:9104IDE_root_spark_7，请求状态接口时报500

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
You need to look at the log of linkis-cg-entrance to see the reason for the error
