### ISSUE TITLE
[Bug] （Linkis Management Desk issue record）Linkis管理台问题记录

### ISSUE THREAD

**Issue by jacktao007** [apache/linkis#3751]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-web

### Basic Data Management（基础数据管理）

1. Token management, added error reporting （令牌管理，新增报错）
![1](https://user-images.githubusercontent.com/1073365/199249527-485a3fb2-ae3b-448c-843a-ec2e189f63ca.png)
![2](https://user-images.githubusercontent.com/1073365/199249657-73b8fe90-737a-4441-b3e0-572945a93ebd.png)
![3](https://user-images.githubusercontent.com/1073365/199249739-fd662d63-8575-4481-b513-5e34e6499ad4.png)

2. Token management delete error（令牌管理 删除报错）
![4](https://user-images.githubusercontent.com/1073365/199250182-f1d2df19-9e4f-4cb5-bdd5-6911813de38e.jpg)

3. Extended resource management added an error（扩展资源管理 新增报错）
![5](https://user-images.githubusercontent.com/1073365/199250316-e12d7507-e38b-4dbd-a222-07f0c493be59.png)
![6](https://user-images.githubusercontent.com/1073365/199250397-c26e8304-f79e-44d5-acbf-12a1e53408e6.png)

4.Extended resource management modifications (front-end issues)（扩展资源管理 修改 (前端问题)）  
![7](https://user-images.githubusercontent.com/1073365/199250980-a2250aae-1b68-4460-80b3-5d520285037a.png)
![8](https://user-images.githubusercontent.com/1073365/199251099-7b067102-aeb5-4f67-9022-637dc723f693.png)

Shows that the edit failed with the data unchanged, but reloads the page to show the modified data（显示编辑失败，且数据未修改，但是刷新页面后显示修改后数据）  

5. Extended resource management to remove bugs (front-end issues)  （扩展资源管理，删除bug (前端问题)）  
![9](https://user-images.githubusercontent.com/1073365/199251272-93aea9b8-6c33-4e59-8b80-0915dcf7b1f8.png)
The data is not refreshed. The data is deleted after the page is refreshed（显示删除失败，数据未刷新，页面刷新后数据删除）  

6. Engine material management Update engine plugins (front-end issues)（引擎物料管理 更新引擎插件 (前端问题)）  
![10](https://user-images.githubusercontent.com/1073365/199251468-4dd310f3-2f61-4179-9c52-4f56b0f81a2f.png)

7. Engine material management button is not checked (you must select engine and version before operation) (front-end problem)（引擎物料管理 按钮未做校验(必须先选择引擎和版本再进行操作) (前端问题)）  

![11](https://user-images.githubusercontent.com/1073365/199251771-da77530d-c036-4c53-9073-4f410409bd09.png)

Engine Material management failed to delete engine  （引擎物料管理 删除引擎失败）  
![12](https://user-images.githubusercontent.com/1073365/199251922-b8e078fc-e066-48a1-ba2a-a89ea5a855a2.png)

### Data source management  （数据源管理）  
1.Data source environment added successfully Data not updated (front-end issue)（数据源环境  添加成功数据未更新 (前端问题)）  
![13](https://user-images.githubusercontent.com/1073365/199252180-19f87e58-474d-4c51-bfc0-c920902c411d.png)
![14](https://user-images.githubusercontent.com/1073365/199252278-4d717f20-ad5f-412c-a92b-8ce8ca250cde.png)

2.Data source classification Add error Add successful data not refrefied (front-end issue)  （数据源分类 添加错误 添加成功数据未刷新 (前端问题)）  
![15](https://user-images.githubusercontent.com/1073365/199252402-7557d1f7-ba71-483d-a3e6-4e5d2fd362c1.png)
After the refresh（刷新后）  
![16](https://user-images.githubusercontent.com/1073365/199252546-70f44eaf-e40f-4940-9fea-09e1200bf916.png)
3.Data source classification modification validation error (front-end issue)（数据源分类  修改校验错误 (前端问题)）  
![18](https://user-images.githubusercontent.com/1073365/199252697-ef6b7121-9625-4440-a698-f989e91ba92c.png)

4.Data source classification deleted successfully Data has not been updated (front-end issue)（数据源分类 删除成功 数据未刷新 (前端问题)）  
![19](https://user-images.githubusercontent.com/1073365/199252844-59be99e8-3cce-4190-b5f8-42154531fbb0.png)

5.Data source permission added error（数据源权限 新增错误） 
![20](https://user-images.githubusercontent.com/1073365/199253019-20d3fa60-c872-4fc7-ae97-7bd905ad4d4f.png)
![21](https://user-images.githubusercontent.com/1073365/199253108-9115abe2-f5cb-4c81-a57f-c8cba9c35654.png)

### UDF function （UDF函数）   
1.Function management added error (script path cannot be modified and data validation fails) (front-end issue)（函数管理 新增报错（脚本路径不可修改，且数据校验不通过）(前端问题)） 

![22](https://user-images.githubusercontent.com/1073365/199253332-d7b1f0dd-1f4e-4e9e-ba2a-9a0ff0310db8.png)

2.User management added an error（用户管理 新增报错）  

![23](https://user-images.githubusercontent.com/1073365/199253471-418d9e68-0e3e-4a7a-acc8-221357abd6fd.png)

3.User management added error UDF classification added exception (parent key did not do numerical verification) (front-end issue)（UDF分类 新增异常(父级key未做数字校验) (前端问题)）  

![24](https://user-images.githubusercontent.com/1073365/199253656-9648e77b-e92a-4875-8747-cdf3573c8cf5.png)
![25](https://user-images.githubusercontent.com/1073365/199253748-9d548193-8b71-4cee-8af0-6a0b95cc8a39.png)

4.UDF classification new exception added successful data not updated (front-end problem) （UDF分类 新增异常 添加成功数据未更新 (前端问题)）  

![26](https://user-images.githubusercontent.com/1073365/199253853-8faf1f6e-14f0-4202-a7e9-fec9e5f7a5d7.png)

5.Other （其它）  
Remove author information （去掉作者信息）  

![27](https://user-images.githubusercontent.com/1073365/199254070-229244e3-6e0d-46f8-be9e-0341a1fc505b.png)

### Expected behavior

Is there an exception when merging? I remember that some of them have been modified.

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by casionone** [comment]
2022/11/20 

模糊搜索 优化 placeholder增加对模糊字段的说明 
![企业微信截图_16689196444052](https://user-images.githubusercontent.com/7869972/202887468-682d2481-f0f1-4bb5-9af7-513ff05bc7e0.png)

部分输入栏 增加示例说明和类型限制 
![企业微信截图_16689197092654](https://user-images.githubusercontent.com/7869972/202887474-2246f25f-c2c8-4322-9097-050d23b834d0.png)


![企业微信截图_16689198206904](https://user-images.githubusercontent.com/7869972/202887479-a240ead3-d809-4993-bdd7-132c5d227daf.png)

![企业微信截图_16689198599284](https://user-images.githubusercontent.com/7869972/202887483-53e38ca6-456f-45ba-bbb2-7a3d491200cc.png)

数据源配置项 部分字段补充和类型的展示 
![企业微信截图_16689200629816](https://user-images.githubusercontent.com/7869972/202887488-1067a5e9-f8c4-46de-b669-a39de6188d9d.png)

![企业微信截图_16689202012061](https://user-images.githubusercontent.com/7869972/202887491-f1889f42-5f38-48d7-9a6d-33436a34ab5e.png)

![企业微信截图_16689202692724](https://user-images.githubusercontent.com/7869972/202887497-c5ddf042-571c-41de-935e-c1aac7a6705f.png)

![企业微信截图_16689203713166](https://user-images.githubusercontent.com/7869972/202887511-a02faf16-30cd-4a64-a55d-8e3cc5a2ac08.png)


![企业微信截图_16689220305975](https://user-images.githubusercontent.com/7869972/202887518-27194512-6c8f-46dc-9e51-1045ffe74ed5.png)
新增后  再次新增未重置输入框


![企业微信截图_16689227084275](https://user-images.githubusercontent.com/7869972/202887525-59954b92-7b0e-43fe-8836-3aecc1a86603.png)
![企业微信截图_16689227191492](https://user-images.githubusercontent.com/7869972/202887527-b049ffc2-b380-4dfd-ace6-39f041f5ffba.png)

udf分类新增数据 填充的创建时间  CURRENT_TIMESTAMP 相差12小时（未24小时制）？
实际时间  2022-11-20 13:45
数据库表记录时间 2022-11-20 01:45 

引擎物料管理页面的优化调整 
![企业微信截图_1668923405370](https://user-images.githubusercontent.com/7869972/202887695-b0b5bcef-1c22-4206-b576-c0b3e499a3d1.png)
