### ISSUE TITLE
[Question] When i use linkis There are some questions 

### ISSUE THREAD

**Issue by Zdddddddddddd** [apache/linkis#3802]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.0
- Environment name and version:
    - hdp-2.7.7
    - hive-2.3.3
    - spark-2.4.3
    - jdk 1.8.0_121
   

### Describe your questions

Q1.  ...
When I use Hql on Linkis There some errors

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)
![image](https://user-images.githubusercontent.com/99249117/200719714-2a3c73d3-44c9-4320-ab2e-cc5892ab700f.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
[log.zip](https://github.com/apache/incubator-linkis/files/9966701/log.zip)

log file:

**Comment by jacktao007** [comment]
-

   Let's see if there's something wrong with the path configuration
   -

   (看一下是否路径配置的有问题)


Zdddddddddddd ***@***.***> 于2022年11月9日周三 10:09写道：

**Comment by Zdddddddddddd** [comment]
![image](https://user-images.githubusercontent.com/99249117/200722182-9cff177f-e56a-4e40-a49c-b3308398e942.png)
 This dir  is right?

**Comment by casionone** [comment]
yes, it is right.
