### ISSUE TITLE
[Question] When i use hql on linkis There are some errors  help me please

### ISSUE THREAD

**Issue by Zdddddddddddd** [apache/linkis#3804]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.0
- Environment name and version:
    - hdp-2.7.7
    - hive-2.3.3
    - spark-2.5.4
    - jdk 1.8.0_121
    

### Describe your questions

Q1. I install as https://linkis.apache.org but I still some errors 

### Eureka service list

[Uploading image.png…]()

### Some logs info or acctch file

[logs.zip](https://github.com/apache/incubator-linkis/files/9967675/logs.zip)

**Comment by ruY9527** [comment]
Hello, is there any missing jars under the convenient update to deal with this problem?
---
你好,方便更新下缺少那些jar处理掉这个问题的吗?

**Comment by Zdddddddddddd** [comment]
It's not the same error

**Comment by jacktao007** [comment]
org.apache.linkis.orchestrator.ecm.exception.ECMPluginErrorException: errCode: 12003 ,desc: hadoop105:9101_48 Failed  to async get EngineNode AMErrorException: errCode: 30002 ,desc: ServiceInstance(linkis-cg-engineconn, hadoop105:42033) ticketID:33ef7680-6019-495c-96da-e8ca7aa928b7 初始化引擎失败,原因: Failed to start EngineConn, reason: ECMErrorException: errCode: 11102 ,desc: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0
Whether the version is incompatible?

**Comment by jackxu2011** [comment]
> org.apache.linkis.orchestrator.ecm.exception.ECMPluginErrorException: errCode: 12003 ,desc: hadoop105:9101_48 Failed to async get EngineNode AMErrorException: errCode: 30002 ,desc: ServiceInstance(linkis-cg-engineconn, hadoop105:42033) ticketID:33ef7680-6019-495c-96da-e8ca7aa928b7 初始化引擎失败,原因: Failed to start EngineConn, reason: ECMErrorException: errCode: 11102 ,desc: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0 Whether the version is incompatible?

这个在新的版本里已经修复了

**Comment by Zdddddddddddd** [comment]
about dss1.0.0 and linkis 1.1.0

**Comment by casionone** [comment]
This question has not been answered for a long time, I will close it first, if necessary, you can re-open it.
