### ISSUE TITLE
[Question] when dss integerate qualitis,i can't login qualitis in dss web pag without entering qualitis's username and password

### ISSUE THREAD

**Issue by 906460** [apache/linkis#3822]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
       cdh-5.14.2
       hdp-2.7.2
       hive-2.3.3
       spark-2.4.3
       scala-2.11.12
       jdk 1.8.0_201

### Describe your questions

 I can login dss in dss web pag,and login qualitis in qualitis web pag.But when dss integrate qualits,I found something wrong. when  I click the qualitis' link in dss web pag, the qualitis'web  ask me to entering username and password. please look the pictures in the behind.
(1)My configuration step is obey  the official's method:
《接入工作流指南》（[https://github.com/WeBankFinTech/Qualitis/blob/master/docs/zh_CN/ch1/%E6%8E%A5%E5%85%A5%E5%B7%A5%E4%BD%9C%E6%B5%81%E6%8C%87%E5%8D%97.md）](https://github.com/WeBankFinTech/Qualitis/blob/master/docs/zh_CN/ch1/%E6%8E%A5%E5%85%A5%E5%B7%A5%E4%BD%9C%E6%B5%81%E6%8C%87%E5%8D%97.md%EF%BC%89)
(2)  I also read the others' issues in github,and made some adjust in configuration .for example:
 《dss访问qualitis和schedulis组件能够实现免密登录》(https://github.com/WeBankFinTech/DataSphereStudio/issues/954)

![image](https://user-images.githubusercontent.com/39142791/201556724-f1b608b7-4dc8-477f-baec-1b07fd099ea0.png)

### Eureka service list

![image](https://user-images.githubusercontent.com/39142791/201556870-21b2ba9c-3370-4b4d-99df-b3655ba94670.png)

### Some logs info or acctch file

![image](https://user-images.githubusercontent.com/39142791/201556948-67d455d8-4879-4469-acd1-9774878b1aa8.png)

**Comment by KangTomwk** [comment]
hi，Take a look at this issue，https://github.com/WeBankFinTech/DataSphereStudio/issues/954（The dss can access the qualitis component to achieve password free login），Pr can refer to https://github.com/WeBankFinTech/DataSphereStudio/pull/960

**Comment by 906460** [comment]
> hi，Take a look at this issue，[https://github.com/WeBankFinTech/DataSphereStudio/issues/954（The](https://github.com/WeBankFinTech/DataSphereStudio/issues/954%EF%BC%88The) dss can access the qualitis component to achieve password free login），Pr can refer to [WeBankFinTech/DataSphereStudio#960](https://github.com/WeBankFinTech/DataSphereStudio/pull/960)

Before write this issue,i already read this method,and do some modify.But it does not work.
