### ISSUE TITLE
[Feature][linkis-mg-eureka] Eureka should support metadata like version 

### ISSUE THREAD

**Issue by Alexkun** [apache/linkis#3989]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

Eureka should support metadata like version 

For distributed deployment, you need to view the current running version information of all services
It can be solved by eureka metadata. When the service is registered, bring additional metadata information such as version

-----
对于分布式部署时，需要查看所有服务的当前运行版本信息 
可以通过eureka元数据来解决，服务注册时 带上额外的版本等元数据信息 

### Solutions

1, eureka read metadata in linkis-env.sh
2, every service carries the version on the startup

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by GuoPhilipse** [comment]
hello ,I want to have a try ,is it ok ?
