### ISSUE TITLE
[Bug] The compatibility of the versions of dss 1.1.1 and linkis 1.3.1

### ISSUE THREAD

**Issue by zhangwejun** [apache/linkis#4071]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### Steps to reproduce

1.The dss references the linkis1.3.1 version
2.Maven cleaning compilation
3.Could not find package for org.apache.commons.lang.StringUtils

### Expected behavior

Compile normally

### Your environment

- Linkis version used: 1.3.1
- Environment name and version:
dss 1.1.1

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jackxu2011** [comment]
> ### Search before asking
> * [x]  I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.
> 
> ### Linkis Component
> linkis-commons
> 
> ### Steps to reproduce
> 1.The dss references the linkis1.3.1 version 2.Maven cleaning compilation 3.Could not find package for org.apache.commons.lang.StringUtils
> 
> ### Expected behavior
> Compile normally
> 
> ### Your environment
> * Linkis version used: 1.3.1
> * Environment name and version:
>   dss 1.1.1
> 
> ### Anything else
> _No response_
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I am willing to submit a PR!

the dependency should be managed by dss,  not depend on linkis
