### ISSUE TITLE
[Question] Using Spark3.2.1 engine exception errCode: 10000 method call failed AbstractEngineResourceFactory.$ init$

### ISSUE THREAD

**Issue by yyh2954360585** [apache/linkis#4083]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.0
- Environment name and version:
    - hdp-3.2.2
    - hive-3.1.2
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121

### Describe your questions

Q1.  When I execute the script using the Spark3.2.1 engine installed by myself, the initialization of the engine fails.

### Eureka service list

eg:
![image](https://user-images.githubusercontent.com/65161474/210311888-4d8ea819-e3f2-4a14-ba57-f46a95165536.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-cg-engineplugin.log](https://github.com/apache/linkis/files/10334703/linkis-cg-engineplugin.log)
[linkis-cg-entrance.log](https://github.com/apache/linkis/files/10334704/linkis-cg-entrance.log)
[linkis-cg-linkismanager.log](https://github.com/apache/linkis/files/10334705/linkis-cg-linkismanager.log)

**Comment by XXwhite** [comment]
After compiling with scala 1.12, I also encountered this problem
