### ISSUE TITLE
[Feature][Linkis-commons] support different hadoop version compile

### ISSUE THREAD

**Issue by GuoPhilipse** [apache/linkis#4109]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/linkis/issues) and found no similar feature requirement.

### Problem Description

1、some dependency was redundant, we may optimize it.
2、current hadoop version is fixed ,we need to change source code to get package with different hadoop version, we may support compile with hadoop profile

### Description

1、some dependency was redundant, we may optimize it.
2、support compile with different hadoop versio ,user no need to modify source code to get linkis package with hadoop3 or hadoop2 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jackxu2011** [comment]
I found,  the spark2.4.3  just have hadoop 3.1 profile.    is it support hadoop 3.3?
