### ISSUE TITLE
[Bug] Linkis 1.3.0 compile spark3.2.2 version error

### ISSUE THREAD

**Issue by Mrzsy** [apache/linkis#4112]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-engineconnn-plugin

### Steps to reproduce

1、Go to linkis-engineplugin-spark model
2、Change Spark dependency version to 3.2.2 and Scala binary version to 2.12
3、Compile this model
4、See error

### Expected behavior

Compile successful

### Your environment

- Linkis version used: 1.3.0
- Environment name and version:
    - spark-3.2.2
    - scala-2.12.15
    - jdk 1.8.0
    - ....

### Anything else

Error class is SparkSQLHistoryParser.scala,at line 265

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by ChenNengNeng** [comment]
[#2408 ](https://github.com/apache/linkis/issues/2408)，将 c.child 更改为 c.plan。修改后我编译通过了

**Comment by Mrzsy** [comment]
> [#2408](https://github.com/apache/linkis/issues/2408)，将c.child改为c.plan。修改后我编译通过了

Thank you. I compiled it, too.
