### ISSUE TITLE
[Question] linkis linkis-cg-engineplugin  Failed to start

### ISSUE THREAD

**Issue by Mrzsy** [apache/linkis#4122]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.2.0
- Environment name and version:
    - hive-3.1.3
    - spark-3.2.2
    - scala-2.12.15
    - jdk 1.8.0_121
    - ....

### Describe your questions

Begin to check cg-engineplugin
Is local execution:sh /data/dss/dss_linkis_one-click_install_20221201/linkis/sbin/linkis-daemon.sh status cg-engineplugin
ERROR: your linkis-cg-engineplugin microservice is not start successful !!! ERROR logs as follows :
Please check  detail log, log path :/data/dss/dss_linkis_one-click_install_20221201/linkis/logs/linkis-cg-engineplugin.log

### Eureka service list

![image](https://user-images.githubusercontent.com/50099368/212825022-b2378d78-754a-424b-9f75-625a228bb6ef.png)

### Some logs info or acctch file

[ERROR] [Linkis-Default-Scheduler-Thread-1       ] o.a.l.e.s.s.DefaultEngineConnResourceService (91) [$anonfun$run$4] - Failed to
upload engine conn to bml, now exit! org.apache.linkis.httpclient.exception.HttpClientResultException: errCode: 10905 ,desc: URL /api/rest_j/v1/bml/upload request failed! ResponseBody is {"method":null,"status":1,"message":"error code(错误码): 60050, error message(错误信息): The first upload of the resource failed(首次上传资源失败).","data":{"errorMsg":{"serviceKind":"linkis-ps-publicservice","level":2,"port":9105,"errCode":50073,"ip":"****","desc":"The commit upload resource task failed(提交上传资源任务失败):errCode: 60050 ,desc: The first upload of the resource failed(首次上传资源失败) ,ip: **** ,port: 9105 ,serviceKind: linkis-ps-publicservice"}}}. errCode: 10905 ,desc: URL /api/rest_j/v1/bml/upload request failed! ResponseBody is {"method":null,"status":1,"message":"error code(错误码): 60050, error message(错误信息): The first upload of the resource failed(首次上传资源失败).","data":{"errorMsg":{"serviceKind":"linkis-ps-publicservice","level":2,"port":9105,"errCode":50073,"ip":"****","desc":"The commit upload resource task failed(提交上>传资源任务失败):errCode: 60050 ,desc: The first upload of the resource failed(首次上传资源失败) ,ip: **** ,port: 9105 ,serviceKind: linkis-ps-publicservice"}}}. ,ip: **** ,port: 9103 ,serviceKind: linkis-cg-engineplugin ,ip: **** ,port: 9103 ,serviceKind: linkis-cg-engineplugin

**Comment by casionone** [comment]
Can refer to https://linkis.apache.org/zh-CN/docs/latest/deployment/deploy-quick#82-%E6%A3%80%E6%9F%A5%E5%BC%95%E6%93%8E%E7%89%A9%E6%96%99%E8%B5%84%E6%BA%90%E6%98%AF%E5%90%A6%E4%B8%8A%E4%BC%A0%E6%88%90%E5%8A%9F

**Comment by QuantumXiecao** [comment]
Besides the possibilities explained in the docs above, there might be another possibility of hdfs version inconsistency(such as your env is hdfs 3 but you use hdf2 client) which might cause hdfs client configuration error. Just for the record.

**Comment by casionone** [comment]
Without further feedback, I closed this issue. You can reopen if necessary
