### ISSUE TITLE
[Question] Failed to initialize engine

### ISSUE THREAD

**Issue by Mrzsy** [apache/linkis#4132]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    -hadoop 3.2.2
    - hive-3.1.3
    - spark-3.2.2
    - scala-2.12.15
    - jdk 1.8.0_121
    - ....

### Describe your questions

ERROR Job with execId-IDE_hadoop_hive_0 + subJobId : 9 execute failed,21304, Task is Failed,errorMsg: errCode: 12003 ,desc: ip:9101_0 Failed to async get EngineNode AMErrorException: errCode: 30002 ,desc: ServiceInstance(linkis-cg-engineconn, ip:36207) ticketID:4d92c2c2-97cc-4108-a3f4-6573ffd6ce59 初始化引擎失败,原因: ServiceInstance(linkis-cg-engineconn, ip:36207): log dir: /appcom/tmp/hadoop/20230131/hive/4d92c2c2-97cc-4108-a3f4-6573ffd6ce59/logs,NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V ,ip: *****,port: 9101 ,serviceKind: linkis-cg-linkismanager ,ip: **** ,port: 9104 ,serviceKind: linkis-cg-entrance

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/linkis/files/9219529/yarn-error.log)

**Comment by casionone** [comment]
If you use hive 3+ version need some work to adapt  refer to  https://linkis.apache.org/zh-CN/docs/latest/deployment/version-adaptation

**Comment by Mrzsy** [comment]
> 如果你使用 hive 3+ 版本需要一些工作来适应参考 https://linkis.apache.org/zh-CN/docs/latest/deployment/version-adaptation

After modifying these configurations, it is still 初始化引擎失败

**Comment by casionone** [comment]
> > 如果你使用 hive 3+ 版本需要一些工作来适应参考 https://linkis.apache.org/zh-CN/docs/latest/deployment/version-adaptation
> 
> After modifying these configurations, it is still 初始化引擎失败

Can you give some details log information

**Comment by casionone** [comment]
Without further feedback, I closed this issue. You can reopen if necessary
