### ISSUE TITLE
安装后如何切换引擎版本？

### ISSUE THREAD

**Issue by XXwhite** [apache/linkis#4134]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Describe your questions

Q1.  我的集群hive版本是2.1.1-cdh6.3.2，linkis默认hive殷勤的版本是2.3.2，在执行hive脚本时报错：Invalid method name: 'get_table_req'，所以我编译了2.1.1-cdh6.3.2版本的引擎，并更改了一些配置文件，并重启了引擎模块，但无法生效，依然报错。
![image](https://user-images.githubusercontent.com/37920314/215936260-a9114e17-760c-4ab3-abb9-56e9c3830fb9.png)

**Comment by casionone** [comment]
can refer to https://linkis.apache.org/zh-CN/docs/latest/deployment/version-adaptation#7-cdh%E7%89%88%E6%9C%AC%E9%80%82%E9%85%8D
