### ISSUE TITLE
 [Feature ]HiveEngineConn supports concurrency

### ISSUE THREAD

**Issue by binbinCheng** [apache/linkis#4175]
**需求内容**
1. hiveEngineConn支持并发，类似于hiveServer2的体验，减少启动引擎的资源占用

------

**Required content**
1. hiveEngineConn supports concurrency, similar to the experience of hiveServer2, reducing the resource consumption of starting the engine

**Comment by CharlieYan24** [comment]
I would like claim this feature.(hiveEngineConn supports concurrency, to reducing the resource consumption of starting the engine). Could it be assignment to me ? Thanks.
