### ISSUE TITLE
 [Feature ][ECM ]ECM takes over EC

### ISSUE THREAD

**Issue by binbinCheng** [apache/linkis#4184]
**描述**：ECM接管EC
**模块**：ECM 
**需求内容**
1. ECM重启时可选不kill引擎，并且能接管现有存活引擎

------

**Description**: ECM takes over EC
**Module**: ECM
**Required content**
1. When the ECM restarts, you can choose not to kill the engine, and it can take over the existing surviving engine

**Comment by CharlieYan24** [comment]
I would like claim this feature. Could it be assignment to me ? Thanks.

**Comment by jackxu2011** [comment]
> 

ok
