### ISSUE TITLE
 [Feature ]LKIP-26 Linkis removes the underlying engine dependency optimization feature

### ISSUE THREAD

**Issue by binbinCheng** [apache/linkis#4186]
**描述**：LKIP-26 Linkis去底层引擎依赖优化特性
**需求内容**
1. EngineConn不再打入底层引擎的依赖
2. 移除json 4s依赖

------

**Description**: LKIP-26 Linkis removes the underlying engine dependency optimization feature
**Required content**
1. EngineConn no longer imports the dependencies of the underlying engine
2. Remove json 4s dependency

**Comment by peacewong** [comment]
Hello, you can directly reply to the issue to claim it

**Comment by GuoPhilipse** [comment]
hello ,I want to have a try ,is it ok ?
