### ISSUE TITLE
[Feature][Engine] Use OceanBase as Linkis engine

### ISSUE THREAD

**Issue by namewxt1220** [apache/linkis#4218]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/linkis/issues) and found no similar feature requirement.

### Problem Description

I see that Linkis can use MySQL as its underlying engine, so I hope to add OceanBase to the Linkis project as an engine.
OceanBase is a native distributed relational database and is highly compatible with the MySQL protocol. We can use OceanBase just like using MySQL.
OceanBase GitHub: https://github.com/oceanbase/oceanbase

### Description

Use OceanBase as Linkis engine.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
This is a great feature
