### ISSUE TITLE
[Feature][Data source] Linkis data source management support for OceanBase

### ISSUE THREAD

**Issue by namewxt1220** [apache/linkis#4219]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/linkis/issues) and found no similar feature requirement.

### Problem Description

OceanBase is a native distributed database that is highly compatible with the MySQL protocol and we would like to support OceanBase in Linkis data source management.
OceanBase GitHub: https://github.com/oceanbase/oceanbase

### Description

Linkis data source management support for OceanBase.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
This is a great feature, Planned to version Linkis-1.3.3
