### ISSUE TITLE
[Question]  About mdpApi and datasource

### ISSUE THREAD

**Issue by isushao** [apache/linkis#4220]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.0
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-2.4.3
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Describe your questions

Q1.  ...mdqAPI的作用？，其中linkis_ps_datasource_table表里的数据页面上如何操作/如何调用接口进行生成
![image](https://user-images.githubusercontent.com/16602760/219000831-b70bba90-0617-47d0-9156-4dafeec41f1c.png)

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/linkis/files/9219529/yarn-error.log)

**Comment by casionone** [comment]
MdpApi  is old api  to get hive metadata info
About datasource can refer to  https://linkis.apache.org/zh-CN/docs/1.3.2/user-guide/datasource-manual#3--%E6%95%B0%E6%8D%AE%E6%BA%90%E7%9A%84%E4%BD%BF%E7%94%A8
