### ISSUE TITLE
[Bug] hive on tez control panel queue does not take effect and remains the default queue for clients

### ISSUE THREAD

**Issue by hcl3039359** [apache/linkis#4226]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-engineconnn-plugin

### Steps to reproduce

tez-site.xml 默认队列为default、管理台自定义队列为root.default
在代码中增加以下配置，设置tez.queue.name
```
class HiveEngineConnFactory extends ComputationSingleExecutorEngineConnFactory with Logging {

  private val HIVE_QUEUE_NAME: String = "mapreduce.job.queuename"
  private val TEZ_QUEUE_NAME: String = "tez.queue.name"
  private val BDP_QUEUE_NAME: String = "wds.linkis.rm.yarnqueue"
```
```
     .foreach { case (k, v) =>
        logger.info(s"key is $k, value is $v")
        if (BDP_QUEUE_NAME.equals(k)) {
          hiveConf.set(HIVE_QUEUE_NAME, v)
          hiveConf.set(TEZ_QUEUE_NAME, v)
        } else hiveConf.set(k, v)
      }
```
运行hql语句，管理台队列无法生效，依然为默认配置
观察日志队列先被设置为root.default 后 又修改为default

`2023-02-16 03:26:38.916 INFO  [hiveEngineEngine-Thread-2] org.apache.hadoop.hive.ql.exec.tez.TezSessionPoolManager 447 canWorkWithSameSession - Current queue name is root.default incoming queue name is null
2023-02-16 03:26:38.916 INFO  [hiveEngineEngine-Thread-2] org.apache.hadoop.hive.ql.exec.tez.TezSessionPoolManager 351 closeIfNotDefault - Closing tez session if not default: sessionId=6fe7175a-c725-48e8-a899-d16fe45a8329, queueName=root.default, user=hive, doAs=true, isOpen=true, isDefault=false`
`2023-02-16 03:26:39.185 INFO  [hiveEngineEngine-Thread-2] org.apache.hadoop.hive.ql.exec.tez.TezSessionState 562 setupTezParamsBasedOnMR - Config: mr(unset):mapreduce.job.queuename, mr initial value=root.default, tez(original):tez.queue.name=default, tez(final):tez.queue.name=default`
最后报错，因为default队列不存在
`2023-02-16 03:26:39.185 INFO  [hiveEngineEngine-Thread-2] org.apache.hadoop.hive.ql.exec.tez.TezSessionState 562 setupTezParamsBasedOnMR - Config: mr(unset):mapreduce.job.queuename, mr initial value=root.default, tez(original):tez.queue.name=default, tez(final):tez.queue.name=default`

### Expected behavior

hive on tez 管理台队列生效，且其他tez-site配置也希望可以支持不同用户自定义

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Hello, this needs to confirm whether the parameter passed to Hive Ec is the correct queue?

**Comment by casionone** [comment]
Without further feedback, I closed this issue. You can reopen if necessary

**Comment by hcl3039359** [comment]
> Hello, this needs to confirm whether the parameter passed to Hive Ec is the correct queue?

The parameter is correct queue

**Comment by hcl3039359** [comment]
> Without further feedback, I closed this issue. You can reopen if necessary

It maybe changed during executing phase, i'm trying to resolve it . Please reopen this issue.

**Comment by hcl3039359** [comment]
the question is tez queue name is different with console setting, It is same with tez-site.xml whatever console setting
