### ISSUE TITLE
[Question] Can I start the control panel of linkis-web alone ?

### ISSUE THREAD

**Issue by jakiuncle** [apache/linkis#4247]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Describe your questions

Can I start the control panel of linkis-web alone ?

### Some logs info or acctch file

![2RS%83)ZHE9J_5HZ12P9B0O](https://user-images.githubusercontent.com/88994283/220230991-00811641-ec9f-43df-a6c1-61f51adbd1c8.png)

**Comment by casionone** [comment]
The Linkis control panel is compiled as static files. It can be deployed through nginx mapping.   For details, please refer to https://linkis.apache.org/docs/latest/deployment/deploy-console/ 
The Linkis control panel is only a front-end page and needs to be used with the LInkis back-end service interface.

**Comment by jakiuncle** [comment]
I can only start the whole linkis so that linkis-web can run?

**Comment by jakiuncle** [comment]
In fact, I want to add sso function on linkis-web, so I only want to start linkis-web and its back-end module

**Comment by jakiuncle** [comment]
In fact, I want to add sso function on linkis-web, so I only want to start linkis-web and its back-end module

**Comment by casionone** [comment]
You can add my wechat account kinsanities .  We can communicate on wechat.
