### ISSUE TITLE
[Question][Linkis-Web]linkis resource management shows nodata

### ISSUE THREAD

**Issue by xiaomi-box** [apache/linkis#4288]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.3
- Environment name and version:
    - cdh-6.2.0
    - hive-2.1.1
    - spark-2.4.0
    - scala-2.12.2
    - jdk 1.8.0_181
    - ....

### Describe your questions

linkis资源管理显示nodata

### Eureka service list

dss service num 7,linkis service num 10

### Some logs info or acctch file

不知道该看哪里的日志

**Comment by xiaomi-box** [comment]
![1677673767469_A3E987C6-E93B-4fa1-AE17-FFD3AAF606E6](https://user-images.githubusercontent.com/45023902/222139909-63c01ac2-87e6-4ebe-ae82-22f7735427a7.png)

**Comment by xiaomi-box** [comment]
![1677674005285_DBF2BE42-8899-4798-A013-2F4274D5109C](https://user-images.githubusercontent.com/45023902/222140556-f3c13aeb-43f8-4350-8b6d-1bb6d1e3a3b5.png)

**Comment by peacewong** [comment]
No data is normal, only when the engine is started will there be data
