### ISSUE TITLE
[Feature][Meta Database] Linkis uses OceanBase as a meta database

### ISSUE THREAD

**Issue by namewxt1220** [apache/linkis#4345]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/linkis/issues) and found no similar feature requirement.

### Problem Description

OceanBase is a native distributed database, highly compatible with the MySQL protocol and we expect OceanBase to act as a Linkis meta database.
OceanBase GitHub: https://github.com/oceanbase/oceanbase

### Description

Linkis uses OceanBase as a meta database.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by SHOUZIzhang** [comment]
OB can be used as metadata. I'm using version linkis 1.3.0
