### ISSUE TITLE
Sonar code detection problem repair

### ISSUE THREAD

**Issue by binbinCheng** [apache/linkis#4360]
**Sonar code scanning, problem repair**

**example**：
### 1.Cast one of the operands of this multiplication operation to a "double".
![企业微信截图_16786992744757](https://user-images.githubusercontent.com/106590848/224659897-6a4a7c0f-434d-430c-a387-ce7691ffff56.png)
**solve**：
Multiply two long types, the return parameter should be long type(两个long类型相乘，返回参数应为long类型)

### 2.Remove this conditional structure or edit its code blocks so that they're not all the same.
![企业微信截图_16786993147906](https://user-images.githubusercontent.com/106590848/224661144-6499c81f-9f70-426b-9334-88e7414dbb89.png)
**solve**：
The code executed in if else is the same, meaningless code should be removed（if else中执行的代码是一样的，应该去掉无意义的代码）
### 3.This class overrides "equals()" and should therefore also override "hashCode()".
![企业微信截图_16786993418774](https://user-images.githubusercontent.com/106590848/224661783-9a3802bf-d568-4a4f-b579-afb484df2893.png)
**solve**：
rewrite hashCode()（重写hashCode()）

### 5.A "NullPointerException" could be thrown; "res" is nullable here.
![企业微信截图_1678699380841](https://user-images.githubusercontent.com/106590848/224662119-604ead20-b062-445c-9405-a3648911a7b7.png)

**solve**：
Remove meaningless code and perform non-null check before execution（去除无意义代码且执行前应先做非空校验）

### 6.Correct one of the identical sub-expressions on both sides of operator "&&"

![企业微信截图_16786994155850](https://user-images.githubusercontent.com/106590848/224662501-708487f4-e466-4778-a89c-40dd50b79d54.png)

Repeat condition, remove repeat condition（条件重复，去除重复条件）

### 7.Remove this dangerous instance of double-checked locking.(删除这个危险的双重检查锁定实例。)

![企业微信截图_16788446534948](https://user-images.githubusercontent.com/106590848/225183172-df974b50-3fd8-4a10-944b-a89ceca3df22.png)

### 8.Use another way to initialize this instance.(使用另一种方式来初始化这个实例。)
![企业微信截图_16788450596968](https://user-images.githubusercontent.com/106590848/225184042-1217f9f2-eb10-4247-82e8-bdd46d268ce0.png)

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
