### ISSUE TITLE
[Bug] resultsetToExcel interface, when the first row of downloaded data is null except the date, the data download error is reported

### ISSUE THREAD

**Issue by wudixiaomengmeng** [apache/linkis#4364]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-spring-cloud-services

### Steps to reproduce

准备一张带有日期类型的表格，第一行数据除日期外，其他都为空
下载数据选择excel  空字符串

### Expected behavior

下载报错，Caused by: java.lang.NullPointerException
        at org.apache.linkis.storage.excel.StorageExcelWriter.getWorkBook(StorageExcelWriter.scala:63)

### Your environment

- Linkis version used: 1.0.3
- Environment name and version:
    - cdh-6.3.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by casionone** [comment]
Can give more  log info

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
