### ISSUE TITLE
[Question] The Spark task ClassNotFoundException : EngineConnServer error 

### ISSUE THREAD

**Issue by SHOUZIzhang** [apache/linkis#4370]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-3.1.0
    - spark-3.1.1
    - scala-2.12.15
    - jdk 1.8.0_121
    - ....

### Describe your questions

Q1.  ...
执行spark的时候报错

### Eureka service list

spark执行脚本
eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)
![f3e8d5ea17fd0809699638afb35f3cc](https://user-images.githubusercontent.com/96272147/225213205-d1794042-4952-4f43-b8cc-b0431fbf4560.jpg)
lib中jar包
![92d052a4918660a32f8aff89fc2d003](https://user-images.githubusercontent.com/96272147/225213304-b8de4e21-2d46-411d-bc19-1b74a4674ada.jpg)
![63a458e4931f60c97a6ec89ab309e11](https://user-images.githubusercontent.com/96272147/225213350-dad13e02-ad89-4207-81bf-b28db8a389e6.jpg)
![6d8d2c4513577d9f3ebdaa801d3c959](https://user-images.githubusercontent.com/96272147/225213373-3d397304-8221-4bec-953e-5916b100d620.jpg)
![ecdb2521d3e6062724c4a83501e241e](https://user-images.githubusercontent.com/96272147/225213387-46498c7c-de57-42ff-8c4b-9141d2bb2f0f.jpg)
![d2f483fd02ab7a4328884319a5e8b52](https://user-images.githubusercontent.com/96272147/225213401-6e86c8e4-f663-4cb4-893d-4956b5119e80.jpg)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->
![8b2ae42593b32f568defcb3259e441e](https://user-images.githubusercontent.com/96272147/225213973-6544f98d-a35d-4c02-ab47-4c6e43e0623d.jpg)

````
log file:
 
执行报错：
![0eff74652755d93ac688909947ea4eb](https://user-images.githubusercontent.com/96272147/225213778-030ac0e5-3091-4efd-b280-e03e88985336.jpg)

将执行脚本改成cluster模式提交，包找不到类
![bf9f1e5a0459c8623283c8e8fbe4952](https://user-images.githubusercontent.com/96272147/225213628-07a179b0-e08a-48dd-ad5b-439bf61a62b5.jpg)

**Comment by peacewong** [comment]
It is recommended not to install in the home directory, which will cause abnormal file permissions
