### ISSUE TITLE
'proxyUser' should not contain special character '-'

### ISSUE THREAD

**Issue by AshokKuramdasu** [apache/linkis#4372]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.1
- Environment name and version:
    - jdk1.8.0_77

### Describe your questions

bin/linkis-cli -submitUser "x-test" -proxyUser "x-test" -engineType python-python2 -codeType python -code 'print("hello, world!")'

=====Java Start Command=====
exec /data/installations/jdk1.8.0_77/bin/java -server -Xms32m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/installations/apache-linkis-1.3.1-bin/logs/linkis-cli -XX:ErrorFile=/data/installations/apache-linkis-1.3.1-bin/logs/linkis-cli/ps_err_pid%p.log -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=80 -XX:+DisableExplicitGC    -classpath /data/installations/apache-linkis-1.3.1-bin/conf/linkis-cli:/data/installations/apache-linkis-1.3.1-bin/lib/linkis-computation-governance/linkis-client/linkis-cli/*:/data/installations/apache-linkis-1.3.1-bin/lib/linkis-commons/public-module/*: -Dconf.root=/data/installations/apache-linkis-1.3.1-bin/conf/linkis-cli -Dconf.file=linkis-cli.properties -Dlog.path=/data/installations/apache-linkis-1.3.1-bin/logs/linkis-cli -Dlog.file=linkis-client.x-test.log.20230315171045174974931  org.apache.linkis.cli.application.LinkisClientApplication '-submitUser x-test -proxyUser x-test -engineType python-python2 -codeType python -code print("hello, world!")'
[INFO] LogFile path: /data/installations/apache-linkis-1.3.1-bin/logs/linkis-cli/linkis-client.s-maasqa.log.20230315171045174974931
[INFO] User does not provide usr-configuration file. Will use default config
[ERROR] VLD0008,Validation failed: LinkisJob validation failed. Reason: 'proxyUser' should not contain special character '-'

############Execute Error!!!########

### Some logs info or acctch file

bin/linkis-cli -submitUser "x-test" -proxyUser "x-test" -engineType python-python2 -codeType python -code 'print("hello, world!")'

=====Java Start Command=====
exec /data/installations/jdk1.8.0_77/bin/java -server -Xms32m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/installations/apache-linkis-1.3.1-bin/logs/linkis-cli -XX:ErrorFile=/data/installations/apache-linkis-1.3.1-bin/logs/linkis-cli/ps_err_pid%p.log -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=80 -XX:+DisableExplicitGC    -classpath /data/installations/apache-linkis-1.3.1-bin/conf/linkis-cli:/data/installations/apache-linkis-1.3.1-bin/lib/linkis-computation-governance/linkis-client/linkis-cli/*:/data/installations/apache-linkis-1.3.1-bin/lib/linkis-commons/public-module/*: -Dconf.root=/data/installations/apache-linkis-1.3.1-bin/conf/linkis-cli -Dconf.file=linkis-cli.properties -Dlog.path=/data/installations/apache-linkis-1.3.1-bin/logs/linkis-cli -Dlog.file=linkis-client.x-test.log.20230315171045174974931  org.apache.linkis.cli.application.LinkisClientApplication '-submitUser x-test -proxyUser x-test -engineType python-python2 -codeType python -code print("hello, world!")'
[INFO] LogFile path: /data/installations/apache-linkis-1.3.1-bin/logs/linkis-cli/linkis-client.s-maasqa.log.20230315171045174974931
[INFO] User does not provide usr-configuration file. Will use default config
[ERROR] VLD0008,Validation failed: LinkisJob validation failed. Reason: 'proxyUser' should not contain special character '-'

############Execute Error!!!########

**Comment by casionone** [comment]
-submitUser submitted user
-proxyUser specifies the proxy user to execute your code on the Linkis server side optional default submitUser

The user must be a system user that exists on the linux machine

```
-submitUser  提交的用户
-proxyUser  指定在 Linkis 服务器端执行您的代码的代理用户
```
