### ISSUE TITLE
[Bug] publicservice  Table 'linkis.DBS' doesn't exist

### ISSUE THREAD

**Issue by xiaofan2022** [apache/linkis#4411]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-engineconnn-plugin

### Steps to reproduce

1.Compile from document （https://linkis.apache.org/zh-CN/docs/latest/deployment/version-adaptation/#73-cdh632）
2.bin/start-all.sh
3.An error occurs when you enter DataSphere Studio and select the database

### Expected behavior

Is it possible to print out more detailed information? And where did this list come from?

### Your environment

- cdh-6.3.2
- hive-2.1.1
- spark-3.2.1
- scala-2.11.8
- jdk 1.8.0_121
- linkis 1.3.1

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jackxu2011** [comment]
you should set the hive's database for metadata database
