### ISSUE TITLE
How to adapt to Huawei cluster MRS?

### ISSUE THREAD

**Issue by XXwhite** [apache/linkis#4489]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

 linkis 1.3.1

### Describe your questions

I tried to configure the Yarn of Huawei cluster to run SparkSQL, but it was not successful. I checked the source code and found that Huawei Yarn uses the Superior Scheduler and does not provide the/ws/v1/cluster/scheduler interface, which resulted in a resource request failure. Do i need to Rewrite of Linkis based on Huawei cluster, or  have a plans to support Huawei cluster, or are there any other methods? Thanks!

### Eureka service list

none

### Some logs info or acctch file

 
none

**Comment by aiceflower** [comment]
You can modify yarn configuration to Huawei Yarn cluster and execute the spark task again.

refer to https://linkis.apache.org/zh-CN/docs/latest/user-guide/control-panel/basicdata-management/#3-扩展资源管理

If the preceding operations still fail, you need to rewrite Linkis to support Huawei clusters.

There is no plan to support Huawei cluster at present, you can discuss it at Linkis Biweekly meeting.
