### ISSUE TITLE
[Bug] FsPathTest should skip windows

### ISSUE THREAD

**Issue by peacewong** [apache/linkis#4506]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### Steps to reproduce

for windows
mvn clean install

[ERROR] Failures: 
[ERROR]   FsPathTest.testGetSchemaPath:40 expected: <linkis/tmp/data> but was: </tmp/data>

### Expected behavior

no error
should add if (!FsPath.WINDOWS)

### Your environment

windows

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
ping @CharlieYan24

**Comment by CharlieYan24** [comment]
> ping @CharlieYan24

@peacewong Thanks for your kind remind ,I have create PR on this issue .Sorry for later reply.
