### ISSUE TITLE
[Question]When using a user other than hadoop to run the task, there is no permission to get the log on hdfs

### ISSUE THREAD

**Issue by XXwhite** [apache/linkis#4541]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.1
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121

### Describe your questions

I connect dss+linkis to ldap. When I log in as ladp user xiongyi to execute sparksql, I cannot read the log: RemoteException: Permission denied: user=xiongyi, access=EXECUTE, inode="/tmp/linkis/log/ 2023-05-15":hadoop: hadoop:drwxr -x---, I tried to authorize the directory to 777, but a new log directory will be created every day according to the date, the permission is hadoop:hadoop:drwxr-x---, I think the user who created the directory should be hadoop, But it is caused by the logged-in user of the user who read the log. Can this unify users, or is there any other way?

我将dss+linkis接入了ldap，当我使用ladp用户xiongyi登录并执行sparksql时，无法读取日志：RemoteException: Permission denied: user=xiongyi, access=EXECUTE, inode="/tmp/linkis/log/2023-05-15":hadoop:hadoop:drwxr-x---，我曾尝试过将目录赋权777，但是每天都会按照日期创建一个新的日志目录，权限是hadoop:hadoop:drwxr-x--- ，我想应该是创建目录的用户是hadoop，但是读取日志的用户的登录用户导致的，请问这能否统一用户，或者有什么其他办法？

### Eureka service list

None

### Some logs info or acctch file

None

**Comment by aiceflower** [comment]
You can use proxy users or add regular users to the hadoop user group

**Comment by wujian3** [comment]
怎么解决的
