### ISSUE TITLE
[Question]scriptis queries hive errors using hql

### ISSUE THREAD

**Issue by ly-yhq** [apache/linkis#4543]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.2
- Environment name and version:
    - hadoop-2.7.2
    - hive-2.3.3
    - spark-2.4.3
    - scala-2.13.3
    - jdk 1.8.0_351

### Describe your questions

Q1.  使用scriptis的hql查询hive数据报错

### Eureka service list

![image](https://github.com/apache/linkis/assets/44761036/a8252b15-4cac-43c4-897a-9350a5d3f4ee)

### Some logs info or acctch file

hql执行日志:
![image](https://github.com/apache/linkis/assets/44761036/efd86f6e-e8e3-46d3-acac-18ba52af8fde)
````log


<!--日志文字贴到这里-->
2023-05-15 10:51:26.051 ERROR jobRequest(IDE_root_hive_1)  execute failed,21304, Task is Failed,errorMsg: FAILED: SemanticException org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient 
````
log file:
 
[error.txt](https://github.com/apache/linkis/files/11473732/error.txt)

**Comment by aiceflower** [comment]
Normal the linkis does not use datanucleus functions in hive.
You can delete the datanucleus related configuration from the hive configuration and try again.
 $HIVE_HOME/conf/hive-site.xml
