### ISSUE TITLE
[Question]Symptom After linkis integrates jdbc, jdbc query errors are reported

### ISSUE THREAD

**Issue by ly-yhq** [apache/linkis#4551]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.2
- Environment name and version:
    - hadoop-2.7.2
    - hive-2.3.4
    - spark-2.4.3
    - scala-2.13
    - jdk 1.8.0_351

### Describe your questions

Q1.  编译了jdbc引擎后，放到对应目录下，重启linkis服务，配置jdbc连接后，使用报错

![image](https://github.com/apache/linkis/assets/44761036/9f725bb5-7c22-4a9a-8708-f1bdb7872a09)

### Eureka service list

![Snipaste_2023-05-16_19-13-23](https://github.com/apache/linkis/assets/44761036/705b9346-8a64-46d2-b06e-7c3d7bcc6536)

### Some logs info or acctch file

log file:
![Snipaste_2023-05-16_19-15-32](https://github.com/apache/linkis/assets/44761036/1ac538ac-d21b-4abb-9b62-1160b20d694c)

[jdbc.txt](https://github.com/apache/linkis/files/11487183/jdbc.txt)

**Comment by peacewong** [comment]
You need to check the startup script to confirm what is wrong, EngineConnExec.sh

**Comment by ly-yhq** [comment]
> 您需要检查启动脚本以确认出了什么问题，EngineConnExec.sh


The script is executing --engineconn-conf prompt cannot be found, and a number formatting exception was reported in the script and stderr

[stderr.txt](https://github.com/apache/linkis/files/11503849/stderr.txt)
[enginConnExec.txt](https://github.com/apache/linkis/files/11503862/enginConnExec.txt)

**Comment by aiceflower** [comment]
Generally, there is a problem with the configuration of mysql connection information or sql statements. Please check carefully against the usage documentation.
https://linkis.apache.org/zh-CN/docs/latest/engine-usage/jdbc

**Comment by ly-yhq** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ly-yhq** [comment]
> 通常，mysql 连接信息或 sql 语句的配置存在问题。请仔细检查使用文档。 https://linkis.apache.org/zh-CN/docs/latest/engine-usage/jdbc

The URL of jdbc has been verified and there are no issues. An error was reported when verifying EngineConnExec.sh. We hope to receive relevant answers
[jdbc.txt](https://github.com/apache/linkis/files/11862554/jdbc.txt)

**Comment by ly-yhq** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量

**Comment by ly-yhq** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
