### ISSUE TITLE
Consul Support Discussion

### ISSUE THREAD

**Issue by houjunxiong** [apache/linkis#458]
**Is your feature request related to a problem? Please describe.**
Our team is using consul as the spring cloud registration, now we want to integrate linkis into our system, but linkis is using eureka.

我们团队使用Consul作为微服务系统的注册中心，现在想要在系统中引入Linkis的能力，但是Linkis使用了Eureka，因此我们需要在Linkis中添加Consul支持。

**Describe the solution you'd like**
We want to add linkis consul support and we have completed it in version 0.9.3, we add consul support in gateway module, add a new maven profile to package consul dependencies, add a series of new scripts to install and control consul, add a series of new scripts to install other components which using consul as registration. But this has a huge impact on packaging and deployment of Linkis, so we want to discuss this issue with you.

我们团队在0.9.3的版本基础上完成了Linkis迁移到Consul注册中心的工作，包括添加了Gateway模块对Consul的支持，以及修改了一系列为了支持Consul的安装部署脚本、Maven打包Profile等。但是，这一系列变更对Linkis本身的打包和安装部署逻辑有很大的影响，因此希望与大家一起讨论这个问题。

**Describe alternatives you've considered**

**Additional context**

**Comment by jacktao007** [comment]
you join Wedatasphere community and contribute you code.  We will thank a lot.
