### ISSUE TITLE
[Feature] Linkis1.4.0 requirements

### ISSUE THREAD

**Issue by aiceflower** [apache/linkis#4590]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/linkis/issues) and found no similar feature requirement.

### Problem Description

1.4.0需求
- 引擎版本支持连字符，如hive1.1.0-cdh5.12.0 https://github.com/apache/linkis/pull/4246  
- 对不同hive版本的支持  https://github.com/apache/linkis/pull/4255  
- hadoop、spark、hive 默认版本升级为3.x，hadoop-3.3.4、spark-3.2.1、hive-3.1.3 https://github.com/apache/linkis/pull/4263 
- EngineConn去掉底层依赖项 https://github.com/apache/linkis/pull/4278 
- Spark支持多版本编译 3.3+、2.2 https://github.com/apache/linkis/pull/4301 
- Hive引擎连接器支持并发任务 https://github.com/apache/linkis/pull/4359 
- linkis-storage 支持 OSS 文件系统 https://github.com/apache/linkis/pull/4424 
- linkis-storage 支持 s3 文件系统 https://github.com/apache/linkis/pull/4435 
- 移除json4s依赖 https://github.com/apache/linkis/pull/4368 
- 租户标签支持通用配置，如 user-* https://github.com/apache/linkis/pull/4453 
- 增加 Impala引擎连接器插件支持 https://github.com/apache/linkis/pull/4458 
- ECM重启时不kill EC https://github.com/apache/linkis/pull/4452
- Linkis支持多集群 https://github.com/apache/linkis/pull/4460
- 支持tidb数据源 https://github.com/apache/linkis/pull/4486 
- 支持starrocks数据源 https://github.com/apache/linkis/pull/4496 
- 支持Gaussdb数据源 https://github.com/apache/linkis/pull/4513 
- 支持OceanBase数据源 https://github.com/apache/linkis/pull/4581
- 支持postgresql数据库 https://github.com/apache/linkis/pull/4524
- Spark JDBC支持dm和kingbase数据库 https://github.com/apache/linkis/pull/4568
- Spark etl支持excel https://github.com/apache/linkis/pull/4539 
- Spark etl支持redis https://github.com/apache/linkis/pull/4534  
- Spark etl支持RocketMQ https://github.com/apache/linkis/pull/4564 
- Spark etl支持mongo and es https://github.com/apache/linkis/pull/4560 
- Spark etl支持solr https://github.com/apache/linkis/pull/4569 
- Spark etl支持kafka https://github.com/apache/linkis/pull/4563
- Spark etl 支持数据湖 https://github.com/apache/linkis/pull/4538

1.4.0 requirements
- engine version support hyphen https://github.com/apache/linkis/pull/4246
- support different hive version by @GuoPhilipse ain https://github.com/apache/linkis/pull/4255 
- upgrade hadoop\spark\hive default vertion to 3.x https://github.com/apache/linkis/pull/4263
- EngineConn no longer imports the dependencies of the underlying engine https://github.com/apache/linkis/pull/4278
- Support spark3.3+  and spark2.2- compile https://github.com/apache/linkis/pull/4301
- Engine type label support map value https://github.com/apache/linkis/pull/4409 
- HiveEngineConn supports concurrency https://github.com/apache/linkis/pull/4359
- linkis-storage support OSS filesystem https://github.com/apache/linkis/pull/4424
- linkis-storage support s3 filesystem https://github.com/apache/linkis/pull/4435
- remove json4s from linkis https://github.com/apache/linkis/pull/4368
- Entry tenant label supports common configuration https://github.com/apache/linkis/pull/4453
- add impala engineconn-plugin https://github.com/apache/linkis/pull/4458
- do not kill ec when ecm restart  part-1 https://github.com/apache/linkis/pull/4452
- support multiple cluster PART-1 https://github.com/apache/linkis/pull/4460
- Support tidb dataSources https://github.com/apache/linkis/pull/4486
- Support starrocks dataSources https://github.com/apache/linkis/pull/4496
- Support Gaussdb dataSources https://github.com/apache/linkis/pull/4513
- Support oceanbase dataSources https://github.com/apache/linkis/pull/4581
- Added support for postgresql based on dev-1.4.0 https://github.com/apache/linkis/pull/4524
- spark jdbc etl support dm and kingbase https://github.com/apache/linkis/pull/4568
- spark etl support excel and  transformations can be null https://github.com/apache/linkis/pull/4539
- spark etl support redis and jedis2.9.2 upgrade 3.9.0 https://github.com/apache/linkis/pull/4534
- spark etl support RocketMQ https://github.com/apache/linkis/pull/4564
- spark etl support mongo and es https://github.com/apache/linkis/pull/4560
- spark etl support solr https://github.com/apache/linkis/pull/4569
- spark etl support kafka https://github.com/apache/linkis/pull/4563
- spark etl support datalake and add scala-2.12 module https://github.com/apache/linkis/pull/4538

Scala代码转为Java代码，已转换模块

Scala code has been converted to Java code and modules have been converted

- engineconn-plugins-openlookeng  https://github.com/apache/linkis/pull/4474
- engineconn-plugins-shell https://github.com/apache/linkis/pull/4473
- engineconn-plugins-python https://github.com/apache/linkis/pull/4482
- engineconn-plugins-trino https://github.com/apache/linkis/pull/4526
- engineconn-plugins-presto https://github.com/apache/linkis/pull/4514
- engineconn-plugins-elasticsearch https://github.com/apache/linkis/pull/4531

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
