### ISSUE TITLE
[Feature][CICD]Support git action integtation test

### ISSUE THREAD

**Issue by casionone** [apache/linkis#4600]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/linkis/issues) and found no similar feature requirement.

### Problem Description

**Background**
Although some modules currently have unit tests, for the submitted large feature pr, manual code review cannot guarantee whether the service can run normally after the code is merged. For the pr submitted by community students, there is currently no better way to perform automated basic function verification (only the compilation can be guaranteed), and the availability of the service requires manual verification. There is an urgent need for automated integration testing to complete automated testing of new features/service availability after major revisions.

**Achieved goals**
The service can be automatically deployed and verified after the pr is built through git action
1. Whether the service starts normally
2. Whether the basic engine tasks can be submitted normally (the verification of shell/jdbc/python/tasks is prioritized)
    
**How to do**

- Based on git action tools such as Build k8s Cluster or minikuber, use containerized deployment services for verification
- https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster
- https://github.com/marketplace/actions/minikube-single-node-kubernetes-action
- https://www.testcontainers.org/modules/docker_compose/
- testcontainers allows you to start the Docker container through a programming language, and automatically shut down the container after the program test is completed.
- https://github.com/search?q=org%3Aapache+Testcontainers&type=pullrequests

Action general flow

- Build Image to build a mirror apache/linkis:latest and use git cation cache to facilitate other actions
- minikuber load mirror apache/linkis:latest
- Inspection of kubectl commands
- Specify yaml to start the service through kubectl
- Check whether the linkis service is started normally
- Run the script to verify the underlying service
- Write integration tests for some services by using the testcontainers tool

 Tasks

- git action implements linkis code to build mirror and pull up service
- Write integration test cases based on the testcontainer component (differentiated by service)
- 
-----
**背景**
当前虽然部分模块有单元测试，但是对于提交的大特性pr ，人工的code review无法保证合并代码后，服务是否可以正常运行。对于社区同学提交的pr ，当前没有较好的方式，进行自动化的基础功能验证（只能保证编译通过），服务的可用性需要人工验证。迫切的需要自动化的集成测试，完成对新特性/大修改后的服务可用性进行自动测试。

**实现的目标**
能通过git action 对pr 进行构建后自动部署服务，并验证
1.服务是否正常启动
2.基础引擎任务是否可以正常提交(优先实现 shell/jdbc/python/任务的验证)
    
**实现大体思路**

- 基于Build k8s Cluster 或则minikuber 等git action 工具 使用容器化方式部署服务进行验证
-  https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster
- https://github.com/marketplace/actions/minikube-single-node-kubernetes-action
- https://www.testcontainers.org/modules/docker_compose/
- testcontainers 能够让你实现通过编程语言去启动Docker容器，并在程序测试结束后，自动关闭容器。
- https://github.com/search?q=org%3Aapache+Testcontainers&type=pullrequests

Action 大体流程 

- Build Image 构建出镜像  apache/linkis:latest 并且使用git cation 缓存 方便其他动作使用
- minikuber load 镜像   apache/linkis:latest
- kubectl 命令的检查 
- 通过kubectl 指定yaml 启动服务 
- 检查linkis 服务是否正常启动
- 运行脚本验证基础服务 
- 通过使用testcontainers 工具 针对某些服务 编写集成测试代码 

主要task 

- git  action 实现linkis代码构建镜像和拉起服务
- 基于 testcontainer 组件 编写集成测试案例 （按服务区分）

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
