### ISSUE TITLE
[Feature][linkis-dist] Optimize the linkis config file

### ISSUE THREAD

**Issue by v-kkhuang** [apache/linkis#4628]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/linkis/issues) and found no similar feature requirement.

### Problem Description

1. linkis config file  remove  wds  
2. Compatible with old configurations, read the linkis configuration first, and if there is no configuration, query wds.linkis

### Description

![image](https://github.com/apache/linkis/assets/62878639/db1a939a-7305-454a-ab2e-879304c60823)

to  

![image](https://github.com/apache/linkis/assets/62878639/93e13f99-ec67-49ac-9ed1-d9ba916b36b8)

### Use case

none

### Solutions

none

### Anything else

none

### Are you willing to submit a PR?

- [] Yes I am willing to submit a PR!

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
