### ISSUE TITLE
[Bug] [linkis1.4.0]The interface does not support version hyphen parsing

### ISSUE THREAD

**Issue by gjy1043** [apache/linkis#4639]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-computation-governance

### Steps to reproduce

1、Modify the version number to hyphen format, such as 3.1.3-cdh5.12.0，and then install and deploy it
2、Submit hive tasks through API interface：
POST http://134.175.56.219:19888/api/rest_j/v1/entrance/execute
{
"executeApplicationName":"hive",
"executionCode":"show tables;",
"params":{"variable":{},"configuration":{}},
"source":{"scriptPath":"auto_test"},
"labels":{        
  "engineType": "hive-3.1.3-cdh5.12.0",
  "codeType": "hql"
      }
 } 

![hyphen1](https://github.com/apache/linkis/assets/26829024/030a9532-0307-4914-94ca-85692361bf06)
![hyphen2](https://github.com/apache/linkis/assets/26829024/713b4e3b-bd3c-4a8b-a1fd-5c01b9ec3cf8)

### Expected behavior

Parsed successfully, executed successfully

### Your environment

Linkis version used: 1.4.0

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by aiceflower** [comment]
This bug has been fixed, please reference https://github.com/apache/linkis/pull/4246
