### ISSUE TITLE
[Issue] The linkis-web is using Moment.js as a dependency, instead of Day.js?

### ISSUE THREAD

**Issue by CoderSerio** [apache/linkis#4655]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

--

### Describe your questions

`Moment.js` is a deprecated lib for time data handling.
Many other libs NOT working with `Moment.js` now,  like the component `date-picker`  of  `Antd 5` is no longer support the time data formatted by `Moment.js`.

How about replacing it with `Day.js`, which is more stable and lightweight?🤔

### Eureka service list

--

### Some logs info or acctch file

--

**Comment by casionone** [comment]
can evaluate what needs to be adjusted for linkis-web module if we try to  replacing Moment.js  with Day.js

**Comment by casionone** [comment]
This question has not been answered for a long time. I will close it first, if necessary, you can re-open it.
