### ISSUE TITLE
[Question] flink1.14 linkis 1.1.1 how to use?

### ISSUE THREAD

**Issue by xyls82** [apache/linkis#4658]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.1
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - flink-1.14.5
    - 

### Describe your questions

flink 1.14 linkis flink engine 如何使用

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/linkis/files/9219529/yarn-error.log)

**Comment by ChengJie1053** [comment]
> ### 在问之前
> * [x]  I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).
> 
> ### 您的环境
> * 使用的Linkis版本：1.1.1
> * 环境名称和版本：
>   
>   * cdh-5.14.2
>   * hdp-3.1.5
>   * 蜂巢-2.1.1
>   * 火花-3.2.1
>   * Flink-1.14.5
> 
> ### 描述你的问题
> flink 1.14 linkis flink engine 如何使用
> 
> ### 尤里卡服务列表
> 例如：![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)
> 
> ### 一些日志信息或采集文件
> linkis-xxx.log:
> 
> ```
> 
> <！--日志文字贴到这里-->
> ```
> 
> 日志文件：
> 
> [linkis-xxx.log](https://github.com/apache/linkis/files/9219529/yarn-error.log)

Hello, the current flink version supported by linkis is 1.12, there are some differences in the api between different versions of flink, and the flink version will be upgraded to Flink 1.16 in linkis1.5.0

**Comment by ChengJie1053** [comment]
Hello, the current flink version supported by linkis is 1.12, there are some differences in the api between different versions of flink, and the flink version will be upgraded to Flink 1.16 in linkis1.5.0
