### ISSUE TITLE
[Feature][linkis-website] Add supported data source information

### ISSUE THREAD

**Issue by aiceflower** [apache/linkis#4670]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/linkis/issues) and found no similar feature requirement.

### Problem Description

Add supported data source information, such as: clickhouse
![image](https://github.com/apache/linkis/assets/22620332/14ca2027-6071-4406-9e23-57fb7b6b29e6)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhaowenkai111** [comment]
I want to try #4670 Thanks
