### ISSUE TITLE
[Feature][1.4.0] add engine does not exit parameter by default

### ISSUE THREAD

**Issue by aiceflower** [apache/linkis#4674]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/linkis/issues) and found no similar feature requirement.

### Problem Description

add jdbc and trino engine does not exit configuration parameter by default
wds.linkis.engineconn.max.free.time=0
add to linkis-engineconn.properties

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Zhao-LX2000** [comment]
I want to try #4674. Thanks.
