### ISSUE TITLE
[Feature][1.4.0]  Upgrade the dependency package version

### ISSUE THREAD

**Issue by aiceflower** [apache/linkis#4690]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/linkis/issues) and found no similar feature requirement.

### Problem Description

Upgrade dependency packages as described below
![image](https://github.com/apache/linkis/assets/22620332/5a70d19e-aeb3-47a5-a750-0162500ed087)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Zhao-LX2000** [comment]
I want to try #4690. Thanks.
