### ISSUE TITLE
[Question] Download dependency phase If the script fails to be executed repeatedly, will all dependencies be downloaded again

### ISSUE THREAD

**Issue by crazy-cpu** [apache/linkis#4704]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Describe your questions

Q1.  或者说我需要手动下载所有依赖，我如何知道需要哪些，并且版本是什么

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/linkis/files/9219529/yarn-error.log)

**Comment by aiceflower** [comment]
Please describe the process of downloading materials during installation or during task execution.
Normally it would download automatically without human intervention.

**Comment by casionone** [comment]
This question has not been answered for a long time. I will close it first, if necessary, you can re-open it.
