### ISSUE TITLE
[Question][linkis1.1.1] Queue resource shortage

### ISSUE THREAD

**Issue by mymyscle** [apache/linkis#4739]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

linkis:1.1.1

### Describe your questions

明明没有跑什么东西,显示资源不足,报错:12011集群队列CPU资源不足，可以联系组内人员释放资源,请问如何解决或者哪里扩充资源

### Eureka service list

![image](https://github.com/apache/linkis/assets/100459222/8cc91883-fde6-4c13-82be-6664b342aa62)

### Some logs info or acctch file

报错:12011集群队列CPU资源不足，可以联系组内人员释放资源

**Comment by aiceflower** [comment]
As indicated in the prompt，insufficient resources.
Recommended resources: 16c 32 GB

**Comment by casionone** [comment]
This question has not been answered for a long time. I will close it first, if necessary, you can re-open it.
