### ISSUE TITLE
[WIP][Bug] [linkis-website]website bug record

### ISSUE THREAD

**Issue by aiceflower** [apache/linkis#4761]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-web

### Writing errors
1. architecture task-flow writing error
![image](https://github.com/apache/linkis/assets/22620332/5632a17e-7841-4746-97a2-62ab84707491)

2. architecture task-flow 2.2.2
![image](https://github.com/apache/linkis/assets/22620332/26f74584-fea7-4781-9090-ee66ccfbd0b2)
3.  service_isolation 2
![image](https://github.com/apache/linkis/assets/7869972/80dde380-03ec-47e2-b9e4-db56ac3dfeaa)

4. variable 3.1
![image](https://github.com/apache/linkis/assets/7869972/31fbe1e8-e22c-41d9-a70b-0e97be318653)
![image](https://github.com/apache/linkis/assets/7869972/565b0984-b9da-4719-9f83-b610dd4faa83)

5. add-an-engine-conn 2
![image](https://github.com/apache/linkis/assets/7869972/4dec62ea-6120-4bac-a2ee-fb7500b3555a)

### Expected behavior

Write correctly

### Your environment

linkis 1.4.0

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
