### ISSUE TITLE
[Question] How to make yarn excute job using OneTimeApplication? (need to use linkis httpRestFulAPI)

### ISSUE THREAD

**Issue by PelicanMan126** [apache/linkis#4844]
### Before asking

- [x] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.0
- Environment name and version:
    - hdp-2.7.7
    - yarn-2.7.7

### Describe your questions

Q1.  my project is require using httpRestFul to make linkis to excute job, but now, when yarn application finished excute job, it keep alive 30m, i know that yarn is support one time application, but i don't know how to make linkis to do that.
i'm using "/api/rest_j/v1/entrance/submit" this API and i don't know what should i put in the param
我的项目使用linkis的restfulAPI来使linkis执行任务,当linkis调用yarn完成任务后,yarn的application会保持30分钟才会下线(是否默认使用了交互式链接),我了解到yarn支持一次性链接,请问如何调用linkis的API才能够使它变为一次性实例?我使用的是"/api/rest_j/v1/entrance/submit"这个接口,我知道他可以填写param来改变类似Container数量或内存数量等配置,请问能否修改使用的application类型?

### Some logs info or acctch file

no log

**Comment by peacewong** [comment]
By default, it will be idle for 30 minutes to exit, and the parameter support configuration is: wds.linkis.engineconn.max.free.time=3m
You can also add a tag to execute once, and it will automatically exit after the task is executed: "executeOnce": ""

默认会30分钟空闲退出，参数支持配置为：wds.linkis.engineconn.max.free.time=3m
你也可以增加执行一次标签，任务执行完就会自动退出："executeOnce":""
