### ISSUE TITLE
[Question] how to get spark sql explain

### ISSUE THREAD

**Issue by cowcomic** [apache/linkis#4862]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

有两个环境，一个是新版本，如下：
- Linkis version used: 1.3.2
- Environment name and version:
    - spark-3.1.1
    - jdk 1.8.0_121

一个是旧版本
- Linkis version used: 0.9
- Environment name and version:
    - spark-2.4

### Describe your questions

Q1.  执行spark sql的时候如何能够查看explain的结果
如在spark-shell中这样的语句
sql("select count(*) from test_agg").explain(true)

https://linkis.staged.apache.org/zh-CN/docs/1.3.2/user-guide/linkiscli-manual#4-支持的参数列表
shell的文档里没有相关说明

### Some logs info or acctch file

无

**Comment by aiceflower** [comment]
This is supported, you can refer to the following ways to use.
val s=sql("select count(*) from test_agg").explain(true) ; show(s)

**Comment by casionone** [comment]
This question has not been answered for a long time, I will close it first, if necessary, you can re-open it.

**Comment by cowcomic** [comment]
I mean how to get the result of the explain in the IDE instead of using the shell
