### ISSUE TITLE
[Feature][linkis] Safety work order repair

### ISSUE THREAD

**Issue by v-kkhuang** [apache/linkis#4877]
### 需求背景
安全工单修复
### 目标
  avro: 建议升级至1.11.0或以上版本
        ./lib/linkis-engineconn-plugins/sqoop/dist/1.4.6/lib/avro-1.7.4.jar
        ./lib/linkis-engineconn-plugins/flink/dist/1.12.2/lib/avro-1.7.4.jar
        ./lib/linkis-public-enhancements/linkis-ps-metadataquery/service/hive/avro-1.7.4.jar
  
   kafka: 建议升级至3.4.0或以上版本。
        ./lib/linkis-engineconn-plugins/flink/dist/1.12.2/lib/kafka-clients-2.5.1.jar
  
  snappy: 升级到1.1.5及以上版本
        ./lib/linkis-engineconn-plugins/flink/dist/1.12.2/lib/snappy-java-1.1.4.jar
### 处理方案
升级至目标版本

---
### Requirement background
Safety work order repair
### Goal
  avro:  It is recommended to upgrade to version 1.11.0 or above
        ./lib/linkis-engineconn-plugins/sqoop/dist/1.4.6/lib/avro-1.7.4.jar
        ./lib/linkis-engineconn-plugins/flink/dist/1.12.2/lib/avro-1.7.4.jar
        ./lib/linkis-public-enhancements/linkis-ps-metadataquery/service/hive/avro-1.7.4.jar
   kafka: It is recommended to upgrade to version 3.4.0 or above.
        ./lib/linkis-engineconn-plugins/flink/dist/1.12.2/lib/kafka-clients-2.5.1.jar
  snappy: Upgrade to version 1.1.5 and above
        ./lib/linkis-engineconn-plugins/flink/dist/1.12.2/lib/snappy-java-1.1.4.jar
### Processing plan
Upgrade to target version

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
