### ISSUE TITLE
[Feature]History Engine Optimization

### ISSUE THREAD

**Issue by v-kkhuang** [apache/linkis#4878]
### 需求背景
历史引擎新增状态栏展示，页面增加状态搜索栏

### 目标
1.历史引擎新增状态栏展示
2.页面支持页面增加状态搜索栏
3.接口支持搜索栏过滤

### 处理方案
1.前端页面展示状态：引擎类型和标签之间 引擎类型 - 状态- 标签
2.前端增加搜索栏：状态： 
状态数据：/api/linkisManager/listAllNodeHealthyStatus
3.后端接口增加参数过滤：status  接口：ecrHistoryList

---
### Requirement background
The history engine has added a status bar display, and the page has added a status search bar
### Goal
1. New status bar display in the history engine

2. The page supports adding a status search bar to the page

3. The interface supports search bar filtering
### Processing plan
1. Frontend page display status: between engine type and tag, engine type - status - tag

2. Add a search bar on the front end: Status:

Status data:/api/linkisManager/listAllNodeHealthStatus

3. Add parameter filtering to the backend interface: status interface: ecrHistoryList

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
