### ISSUE TITLE
[Feature][error code] linkis add error code

### ISSUE THREAD

**Issue by v-kkhuang** [apache/linkis#4886]
### 需求背景
新增错误码  

### 目标

1.错误码：13008
正则：is bigger than spark.driver.maxResultSize
提示信息：任务产生的序列化结果总大小超过了配置的spark.driver.maxResultSize限制。请检查您的任务，看看是否有可能减小任务产生的结果大小，或则可以考虑压缩或合并结果，以减少传输的数据量 

### 处理方案
1.后端在错误码表中新增

---
### Requirement background
Add error code
### Goal
1. Error code: 13008
Regular: is bigger than spark. driver. maxResultSize
Reminder: The total size of the serialization results generated by the task exceeds the configured spark.driver.maxResultSize limit. Please review your task to see if it is possible to reduce the size of the results generated by the task, or consider compressing or merging the results to reduce the amount of data transmitted
### Processing plan
1. Add a new error code in the backend table

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
