### ISSUE TITLE
[Feature][Module Name] New engine status display on the history engine page, new engine status search

### ISSUE THREAD

**Issue by v-kkhuang** [apache/linkis#4887]
### 需求背景

历史引擎页面新增引擎状态展示，新增引擎状态搜索

### 目标
1.历史引擎页面增加状态栏展示
2.历史引擎页面增加状态搜索栏

### 处理方案
前端：
1.历史引擎页面增加状态栏展示
2.历史引擎页面增加状态搜索栏
后端：
1.接口支持状态栏搜索

---
### Requirement background
New engine status display on the history engine page, new engine status search
### Goal
1. Add a status bar display on the history engine page
2. Add a status search bar to the history engine page
### Processing plan
Front end:
1. Add a status bar display on the history engine page
2. Add a status search bar to the history engine page
Backend:
1. Interface supports status bar search

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
