### ISSUE TITLE
[Feature][1.5.0] Feature list

### ISSUE THREAD

**Issue by CharlieYan24** [apache/linkis#4890]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/linkis/issues) and found no similar feature requirement.

### Problem Description

1.5.0 feature list (Everyone is welcome to add. )

| feature                                                      | owner   | progress|  issue   | pr| self test status | 设计文档| 使用文档|
| -------- | -------|-- | ---- | ---- | ---| -------| -------|
| 示例 |  @test     | 100% |  #test   |  #test    |  done   | 文档地址 | 文档地址 |
| Entrance supports task HA (running task support is taken over) |  @guoshupei     | |     |      |     | | |
| Support task submission to the K8S cluster                   |   @chenghuichen  @Zhao-LX2000    | |     |      |    | | |
| Support spark job to K8S cluster using operator                   |   @ChengJie1053    |    |  |      |    | | |
| Support Nacos                                                |    @wForget   |    completed  |   |   |    | | |
| Entrance supports Orchestrator pluggable                     |      |   |   |      |    | | |
| The once-mode task supports recording information through the entrance |   @CharlieYan24     |      | |     |    | | |
| The data source module supports data source SQL generation and supports more data sources with the Spark ETL function |      |    |  |      |    | | |
| Spring Cloud gateway upgrade version, spring boot upgrade version |      |   |   |      |    | | |
| Monitor service added |  @peacewong    |   in progress|      | |  | | |
| Add task positioning troubleshooting script |  @peacewong    |   done  |   #4904 |  |  | | |

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
