### ISSUE TITLE
[Bug] When trino queries a table containing a decimal field, the metadata of that field is converted to a string

### ISSUE THREAD

**Issue by v-kkhuang** [apache/linkis#4892]
### 异常背景

使用trino查询包含decimal字段的表时，该字段元数据会被转换为string。
![image](https://github.com/apache/linkis/assets/62878639/843184ab-2bca-4fb4-8328-c3616e48784b)

### 重现步骤

1.用户查询语句：select * from leebai_ind.test_alltype_null
2.查看openFile接口返回的元数据：发现decimal类型变为string

---
### Abnormal background
 When using trino to query a table containing a decimal field, the metadata of that field is converted to a string.
### Repro steps
1. User query statement: select * from leebai_ Ind. test_ Alltype_ Null
2. View the metadata returned by the openFile interface: found that the decimal type has changed to string

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
