### ISSUE TITLE
[Bug] When I submit a jar package using the spark engine, I cannot view the submission history

### ISSUE THREAD

**Issue by sjgllgh** [apache/linkis#4893]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-engineconnn-plugin

### Steps to reproduce

1. Use the once mode, execute the spark engine, and submit the jar package

### Expected behavior

1. I want to view the Spark Jar submission records through Linkis Console

### Your environment

- Linkis version used: 1.4.0
- Environment name and version:
    - hdp-3.1.4
    - spark-3.2.1
    - scala-2.12.17

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by aiceflower** [comment]
The Linkis Console does not support viewing. You can view upload records through logs.

**Comment by sjgllgh** [comment]
> 

I just want to view the submission record, not the detailed log. Maybe this is not a bug, should I raise a feature issue again?

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
