### ISSUE TITLE
[Feature][Entrance] run count hql needs to be removed limit 

### ISSUE THREAD

**Issue by sjgllgh** [apache/linkis#4894]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/linkis/issues) and found no similar feature requirement.

### Problem Description

When I execute the count statement using the hive engine, automatically add a limit 5000，eg:

************************************SCRIPT CODE************************************
select count(*) from default.test limit 5000;
************************************SCRIPT CODE************************************
This syntax will increase SQL time consumption

### Description

change category:
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/interceptor/impl/Explain.scala
add:
Add restrictions and exclude count syntax when determining whether SQL needs to add limits

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by aiceflower** [comment]
This prevents slow queries when querying large amounts of data. There are parameters in the code to control the removal of this restriction.

**Comment by sjgllgh** [comment]
Only the count syntax needs to remove the limit restriction.
This type does not have parameter control. If so, please let me know

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
