### ISSUE TITLE
[Question] linkis-web engine interface of does not have an engine instance

### ISSUE THREAD

**Issue by fy403** [apache/linkis#4899]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - flink-1.12.2  
    - hadoop-3.3.4  
    - hive-3.1.3  
    - linkis-1.5.0  
    - scala-2.12.17  
    - spark-3.2.1
    - jdk 1.8.0_121
    - ....

### Describe your questions

# Q1.  我搭建好了linkis，使用命令行可以直接驱动Engine执行，但是linkis-web的引擎界面没有引擎实例，我看了mysql表中，确实存在实例；
## I have built Linkis and can directly drive the Engine to execute using the command line. However, the engine interface of Linkis web does not have an engine instance. I checked the MySQL table and found that there are indeed instances;

# 引擎被加载到指定目录
## The engine is loaded into the specified directory
![image](https://github.com/apache/linkis/assets/51740518/073f345d-6a7c-41e3-bdf7-01b1c2b67678)

# 配置了加载目录
## Configured loading directory
./conf/linkis-cg-linkismanager.properties:24:wds.linkis.engineconn.home=/opt/linkis-1.5.0/lib/linkis-engineconn-plugins
./conf/linkis-cg-linkismanager.properties:25:wds.linkis.engineconn.plugin.loader.store.path=/opt/linkis-1.5.0/lib/linkis-engineconn-plugins

# 日志没有报错
## No errors reported in the log
questUri: /api/rest_j/v1/microservice/modifiableLabelKey with parsedService linkis-ps-publicservice to ServiceInstance(linkis-ps-publicservice, null)
2023-09-05 19:45:22.281 [INFO ] [reactor-http-epoll-1                    ] o.a.l.g.s.h.GatewayAuthorizationFilter (167) [gatewayDeal] [JobId-] - Client request ip: /127.0.0.1:40336 and uri: /api/rest_j/v1/configuration/engineTypeGatewayRouter route requestUri: /api/rest_j/v1/configuration/engineType with parsedService linkis-ps-publicservice to ServiceInstance(linkis-ps-publicservice, null)

# 命令行可以正常使用引擎
## The command line can use the engine normally
$sh bin/linkis-cli -submitUser  hadoop  -engineType spark-3.2.1 -codeType sql  -code "show tables"

# mysql数据库存在引擎数据
## Engine data exists in MySQL database
![image](https://github.com/apache/linkis/assets/51740518/e0158a17-d541-48fb-9d82-b90b9cd4f14f)

# 但是linkis-web没有引擎实例数据
## But linkis web does not have engine instance data
![image](https://github.com/apache/linkis/assets/51740518/23b76464-a98a-4c1b-ac88-384672d2c58a)

### Eureka service list

![image](https://github.com/apache/linkis/assets/51740518/4960e835-efe9-43a8-b679-e203551c39e6)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/linkis/files/9219529/yarn-error.log)

**Comment by aiceflower** [comment]
You can refer to the user documentation on the official website.
By default, the engine instance will be destroyed after the task is completed. You can add the -creator IDE parameter to view the task. Alternatively, you can use Eureka to view engine services during task execution.
The engine supported by Linkis is not the same concept as the engine in operation.
![image](https://github.com/apache/linkis/assets/22620332/13f1fc79-9df8-4467-bc7c-35071a2549e4)

**Comment by fy403** [comment]
Thank you! I got it
