### ISSUE TITLE
Does kyuubi support analysis of zeppelin

### ISSUE THREAD

**Issue by smileyboy2019** [apache/linkis#4921]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/linkis/issues) and found no similar feature requirement.

### Problem Description

Zeppelin is a visual analysis tool that submits Spark code and SparkSQL online

### Use case

Zeppelin, as the main analysis tool for Spark, is more user-friendly for the development of Kyuubi if it supports Spark SQL well and supports context

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by GuoPhilipse** [comment]
hi @smileyboy2019 ,maybe you can ask more questions about ```kyuubi``` from ```https://github.com/apache/kyuubi/issues```
