### ISSUE TITLE
[Feature][ErrorCode] Add error code matching

### ISSUE THREAD

**Issue by v-kkhuang** [apache/linkis#4924]
### 需求背景

部分错误信息未匹配到错误码，根据特定场景新增错误码

### 目标

1.错误码：43016  
2.新增错误码：43017   
3.新增错误码：43018  
4.优化错误码匹配：21001  
		
### 处理方案

1.错误码：43016   提示语：[模块 'xxxx' 没有属性 'xxxxx'，请确认代码引用是否正常] 匹配正则：[AttributeError: '(\S+)' object has no attribute '(\S+)'] 
2.错误码：43017   提示语：[存在参数无效或拼写错误，请确认 %s 参数正确性] 匹配正则：[KeyError: (\(.+\))]
3.错误码：43018   提示语：[ 文件地址( xxxx )错误，请确认路径是否存在] 匹配正则：[FileNotFoundError.*No such file or directory\:\s'(\S+)']
4.错误码：21001  
		更改前：User (\\S+) cannot submit applications to queue (\\S+)
		更改后：User (\\S+) cannot submit applications to queue (\\S+?)(?=\\)

---
### Requirement background
Some error messages did not match the error code, new error codes will be added based on specific scenarios
### Goal
1. Error code: 43016
2. New error code: 43017
3. New error code: 43018
4. Optimize error code matching: 21001
### Processing plan
1. Error code: 43016 Prompt: [Module 'xxxx' does not have attribute 'xxxxx', please confirm if the code reference is normal] Matching regular: [AttributeError: '( S+)' object has no attribute '( S+)']
2. Error code: 43017 Prompt: [There are invalid parameters or spelling errors, please confirm the correctness of the% s parameters] Matching regular: [KeyError: ( (.+))]
3. Error code: 43018 Prompt: [File address (xxxx) error, please confirm if the path exists] Matching regular: [FileNotFoundError. * No such file or
4. Error code: 21001
Before making changes: User (  S+) cannot submit applications to queue (  S+)
After change: User (  S+) cannot submit applications to queue (  S+?) (?= )

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
