### ISSUE TITLE
[Bug] linkis flink manage ec cannot be reused

### ISSUE THREAD

**Issue by Alexkun** [apache/linkis#4938]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-engineconnn-plugin

### Steps to reproduce

1. restart streamis-server
2. change manage mode of task in streamis-server to detach
3. start the task in streamis-server
4. click 'snapshot' in the task
5. see new flink ecs in linkis console

### Expected behavior

The manage ecs cannot be reused. There are many manage flink ecs.

### Your environment

- Linkis version used: 1.4.0
- Streamis version used: 0.3.2

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
