### ISSUE TITLE
[Question] spark任务提交到yarn，一直是Running状态

### ISSUE THREAD

**Issue by lishengming6** [apache/linkis#4943]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Describe your questions

view组件执行sql，spark引擎提交任务到yarn，yarn任务一直在running，前台数据是返回的
疑问：spark引擎的任务到yarn是常驻的吗？我kill掉引擎就发现yarn任务是finished的，有什么方法可以让spark提交到yarn任务执行完状态变成finished吗？
![image](https://github.com/apache/linkis/assets/18570881/37d7f52c-d7a1-4507-9489-b3058d09f146)

![image](https://github.com/apache/linkis/assets/18570881/d60fd3aa-4bb6-4bfb-a31c-1c7f61e5096a)

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/linkis/files/9219529/yarn-error.log)

**Comment by casionone** [comment]
Check whether the yarn service is  ok
You can run the spark-sql command on the machine to see if the task submitted to yarn is normal.

**Comment by peacewong** [comment]
Hello, this is because the Spark engine is reused, so spark is released when idle. You can add the label executeOnce so that the Spark session will exit after executing the task.

**Comment by lishengming6** [comment]
Is linkis 1.3.1 supported? And Where can I add the label？
