### ISSUE TITLE
[Question] What is the purpose of this configuration ‘linkis. upstream. monitor. actask. should.start' ?

### ISSUE THREAD

**Issue by lishengming6** [apache/linkis#4963]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.1
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Describe your questions

Q1.  What is the purpose of this configuration ‘linkis. upstream. monitor. actask. should.start' ?
Q2. The default configuration is true. If modified to false, what impact will it have on the operation of engine tasks？
Q3. I encountered a Python engine log that was constantly logging connection information results, and finally sending a success to send engine heartbeat report to vppapp101:9501, status: Busy, which caused the engine to stick. If it is changed to false, can we avoid this problem?

### Some logs info or acctch file

![image](https://github.com/apache/linkis/assets/18570881/4d440a19-7d25-4baf-8904-034cf283fc71)

**Comment by peacewong** [comment]
Q1. What is the purpose of this configuration ‘linkis. upstream. monitor. actask. should.start' ?
A： This is applicable to EC monitoring whether the Entrance service exists. If it does not exist, kill the running task to prevent empty running
这个适用于EC监控Entrance服务是否存在，如果不存在则kill运行中的任务，防止空跑
Q2. The default configuration is true. If modified to false, what impact will it have on the operation of engine tasks？
A: can set false
Q3. I encountered a Python engine log that was constantly logging connection information results, and finally sending a success to send engine heartbeat report to vppapp101:9501, status: Busy, which caused the engine to stick. If it is changed to false, can we avoid this problem?
A： 这个正常应该不影响任务才对，如果影响到了，可以看看是哪里导致
