### ISSUE TITLE
[Question] [linkis-computation-engineconn] Flow task，ec log Failed to submit task1 scala.MatchError: null

### ISSUE THREAD

**Issue by zslali** [apache/linkis#4970]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

版本信息：linkis1.4.0, dss1.1.2, qualitis0.9.2, hadoop3.1.1, hive3.1.0, spark2.4.5, scala:2.12.17

### Describe your questions

问题描述：在工作流中执行组件，ec的stdout日志中报Failed to submit task1 scala.MatchError: null

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

ec的stdout日志中报Failed to submit task1 scala.MatchError: null

**Comment by zslali** [comment]
解决办法：修改linkis-computation-engineconn模块下的ComputationExecutor.scala文件，在def execute(engineConnTask: EngineConnTask)方法下添加如下代码：
case _ =>
  logger.warn(s"task get response is $executeResponse")

**Comment by peacewong** [comment]
close by #4972
