### ISSUE TITLE
[Question] submitUser become linkis when using Linkis API to submit mission 使用API方式提交任务时,submitUser变成了linkis

### ISSUE THREAD

**Issue by PelicanMan126** [apache/linkis#5028]
### Before asking

- [x] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.2

### Describe your questions

Q1.  When I submit a mission using Linkis API, I'm using token to do permission test, but when job was excuted, the submitUser and excuteUser is linkis, i'm not set this on my request body, it should be my token user

当我用API方式提交请求的时候,我使用的是token方式做权限校验,但是在执行后显示的submitUser和excuteUser却变成了linkis用户,我没有在参数中指定这两个参数,应该使用默认的token用户

**linkis-mg-gateway.log:**
![image](https://github.com/apache/linkis/assets/92132536/c3f0425f-143b-4e2a-8602-aac48ac684d6)
**linkis-cg-entrance.log**
![image](https://github.com/apache/linkis/assets/92132536/9d728dd1-e32a-4781-b003-e766dc9fc175)
**request detail:**
![image](https://github.com/apache/linkis/assets/92132536/e806f2d9-f044-4174-afa3-0ce3ea590708)

**Comment by casionone** [comment]
The tokenuser used is not linkis, but the recorded task, submitted user is linkis?

**Comment by livi12138** [comment]
![微信截图_20240111161828](https://github.com/apache/linkis/assets/156271765/2f343d3d-63d0-4961-b19f-c8659ea31a70)
你可以在这里设置你的执行用户和提交用户，如果不设置默认就是你的部署用户
You can set your execution user and submission user here. If not set, the default will be your deployment user.

**Comment by peacewong** [comment]
> ![微信截图_20240111161828](https://private-user-images.githubusercontent.com/156271765/295840251-2f343d3d-63d0-4961-b19f-c8659ea31a70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NzkxODMsIm5iZiI6MTcwNDk3ODg4MywicGF0aCI6Ii8xNTYyNzE3NjUvMjk1ODQwMjUxLTJmMzQzZDNkLTYzZDAtNDk2MS1iMTlmLWM4NjU5ZWEzMWE3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxMzE0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDY2YWMxYzY1ODAyYzY1ZWM2MzJkYTU3MWUyOGM0MDZkZjZmMTEzMTY3MmI4YzAzNTM1ODcxM2Q2YjcxMTA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4hYw-XUCSEm-VhLuCBfxcuGrHPjRm7LN_031qblQdZA) 你可以在这里设置你的执行用户和提交用户，如果不设置默认就是你的部署用户 You can set your execution user and submission user here. If not set, the default will be your deployment user.
Thank you for your reply. Can you add my WeChat. id:peaceAyton
