### ISSUE TITLE
[Bug] [1.5.0] There is an error in the log, but the repl-java task was executed successfully

### ISSUE THREAD

**Issue by gjy1043** [apache/linkis#5034]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-computation-governance

### Steps to reproduce

sh bin/linkis-cli -engineType repl-1  -code  "import org.apache.commons.lang3.StringUtils;    public void sayHello() { 
        System.out.println(\"hello\");         
        System.out.println(StringUtils.isEmpty(\"hello\"));
    };               
sayHello()"   -codeType repl

![image](https://github.com/apache/linkis/assets/26829024/a2c27285-be1c-4737-bc08-04808acff6fb)

![image](https://github.com/apache/linkis/assets/26829024/dd8e061e-5148-4726-aba1-569b743ef5b8)

### Expected behavior

task executes fail

### Your environment

- Linkis version used: 1.5.0
- Environment name and version:
    - repl-1

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
close #5036
