### ISSUE TITLE
[Bug] [1.5.0] The result of repl-scala task is wrong

### ISSUE THREAD

**Issue by gjy1043** [apache/linkis#5035]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-engineconnn-plugin

### Steps to reproduce

sh bin/linkis-cli -engineType repl-1  -code  "import org.apache.commons.io.FileUtils
import java.io.File
                                                         
val x = 2 + 3;
println(x);
FileUtils.forceMkdir(new File(\"/tmp/linkis_repl_scala_test\"));"   -codeType repl -runtimeMap linkis.repl.type=scala

![企业微信截图_17023614165966](https://github.com/apache/linkis/assets/26829024/c05f10b5-b154-46b3-94d9-d7eee43e3d79)
![image](https://github.com/apache/linkis/assets/26829024/d6c716ca-a767-4ade-89b3-2313b03b9acc)

### Expected behavior

Task executed successfully, and corresponding  result is correct

### Your environment

- Linkis version used: 1.5.0
- Environment name and version:
    - repl-1 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
close #5036
