### ISSUE TITLE
Linkis 1.3. 2 integrated script 1.1. 2 reports an error and cannot enter content in the script input window

### ISSUE THREAD

**Issue by ly-yhq** [apache/linkis#5039]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.2
- Environment name and version:
    - hdp-3.1.4
    - hive-3.1.0
    - spark2-2.3.2
    - jdk 1.8.0_121
    - hadoop 3.1.1
    - scriptis 1.1.2

### Describe your questions

Q1.  部署了linkis1.3.2版本和scriptis1.1.2版本后，刚加载页面时还会报dss-server的错，可以在不使用dss的情况下集成linkis1.3.2和scriptis1.1.2吗？

![Snipaste_2023-12-13_17-55-18](https://github.com/apache/linkis/assets/44761036/5f7ff633-548d-4a29-a801-a9e852fc7628)

Q2.部署了linkis1.3.2版本和scriptis1.1.2版本后，在scriptis页面中，无法输入任何语句（使用scriptis1.1.2版本主要是为了动态数据源的切换）现在无法在脚本输入窗口中输入任何东西，能够加载出已配置的数据源
![image](https://github.com/apache/linkis/assets/44761036/397b835b-b898-4a01-98c3-8eac8e77e1a3)

Q3.出现以上问题是否是因为linkis1.3.2和scriptis存在兼容型问题

### Eureka service list

linkis-cg-enginneconnmanager
linkis-cg-entrance
linkis-cg-linkismanager
linkis-mg-eureka
linkis-mg-gateway
linkis-ps-publicservice
eureka中有上述6个服务存活

### Some logs info or acctch file

[gateway.log](https://github.com/apache/linkis/files/13659318/gateway.log)

![image](https://github.com/apache/linkis/assets/44761036/5cdef014-3955-40fd-a54f-9bee5a2f14da)

**Comment by ly-yhq** [comment]
上文中所指的scriptis1.1.2是指我从dss1.1.2版中中编译出的scriptis版本

**Comment by casionone** [comment]
"在scriptis页面中，无法输入任何语句" 
any error msg at browser debugger mode?
![image](https://github.com/apache/linkis/assets/7869972/65f9ee17-e812-4516-a491-9b8e7e0b879c)

**Comment by ly-yhq** [comment]
> “在scriptis页面中，无法输入任何语句” 浏览器调试模式下的任何错误消息？ ![图像](https://private-user-images.githubusercontent.com/7869972/291023529-65f9ee17-e812-4516-a491-9b8e7e0b879c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODM4NTIsIm5iZiI6MTcwMjk4MzU1MiwicGF0aCI6Ii83ODY5OTcyLzI5MTAyMzUyOS02NWY5ZWUxNy1lODEyLTQ1MTYtYTQ5MS05YjhlN2UwYjg3OWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTA1OTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdkMjhkNzYwNWNiODcyNDRkNTYyOGM1MGQ4MGY2OTg2ZGQ3MGMxODg3ZTc0YWIxZDYxMzgwOWU4YWI5NGNkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.96wJrRISUVD8Qt-Nk48tUU_pfGLCcKjADOMRX-mYOC0)

![image](https://github.com/apache/linkis/assets/44761036/85344fd1-ae47-4163-bbfc-e93ab47f9dbd)

这个是我在打开scriptis页面时的报错截图，在打开jdbc的文件到编辑页面并没有任何输出和报错

**Comment by casionone** [comment]
> > “在scriptis页面中，无法输入任何语句” 浏览器调试模式下的任何错误消息？ ![图像](https://private-user-images.githubusercontent.com/7869972/291023529-65f9ee17-e812-4516-a491-9b8e7e0b879c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODM4NTIsIm5iZiI6MTcwMjk4MzU1MiwicGF0aCI6Ii83ODY5OTcyLzI5MTAyMzUyOS02NWY5ZWUxNy1lODEyLTQ1MTYtYTQ5MS05YjhlN2UwYjg3OWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTA1OTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdkMjhkNzYwNWNiODcyNDRkNTYyOGM1MGQ4MGY2OTg2ZGQ3MGMxODg3ZTc0YWIxZDYxMzgwOWU4YWI5NGNkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.96wJrRISUVD8Qt-Nk48tUU_pfGLCcKjADOMRX-mYOC0)
> 
> ![image](https://private-user-images.githubusercontent.com/44761036/291573686-85344fd1-ae47-4163-bbfc-e93ab47f9dbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjQ0MDMsIm5iZiI6MTcwMzEyNDEwMywicGF0aCI6Ii80NDc2MTAzNi8yOTE1NzM2ODYtODUzNDRmZDEtYWU0Ny00MTYzLWJiZmMtZTkzYWI0N2Y5ZGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyMDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjI0MTBmZGFmYmM2YjU3YTU3MGY0ZTFjNmJmYTA0ODY2OGFmZThkYTBiMGFkM2RjODMzODY2YjZmMDQwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ky27OULN4pvOld1SjgoZWIEbfzURfpjP9Uhu55dfV1Q)
> 
> 这个是我在打开scriptis页面时的报错截图，在打开jdbc的文件到编辑页面并没有任何输出和报错

can you give the detail process about you build scriptis web resource

**Comment by ly-yhq** [comment]
> > > “在scriptis页面中，无法输入任何语句” 浏览器调试模式下的任何错误消息？ ![图像](https://private-user-images.githubusercontent.com/7869972/291023529-65f9ee17-e812-4516-a491-9b8e7e0b879c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODM4NTIsIm5iZiI6MTcwMjk4MzU1MiwicGF0aCI6Ii83ODY5OTcyLzI5MTAyMzUyOS02NWY5ZWUxNy1lODEyLTQ1MTYtYTQ5MS05YjhlN2UwYjg3OWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTA1OTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdkMjhkNzYwNWNiODcyNDRkNTYyOGM1MGQ4MGY2OTg2ZGQ3MGMxODg3ZTc0YWIxZDYxMzgwOWU4YWI5NGNkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.96wJrRISUVD8Qt-Nk48tUU_pfGLCcKjADOMRX-mYOC0)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/44761036/291573686-85344fd1-ae47-4163-bbfc-e93ab47f9dbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjQ0MDMsIm5iZiI6MTcwMzEyNDEwMywicGF0aCI6Ii80NDc2MTAzNi8yOTE1NzM2ODYtODUzNDRmZDEtYWU0Ny00MTYzLWJiZmMtZTkzYWI0N2Y5ZGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyMDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjI0MTBmZGFmYmM2YjU3YTU3MGY0ZTFjNmJmYTA0ODY2OGFmZThkYTBiMGFkM2RjODMzODY2YjZmMDQwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ky27OULN4pvOld1SjgoZWIEbfzURfpjP9Uhu55dfV1Q)
> > 这个是我在打开scriptis页面时的报错截图，在打开jdbc的文件到编辑页面并没有任何输出和报错
> 
> can you give the detail process about you build scriptis web resource

https://linkis.apache.org/zh-CN/docs/latest/deployment/integrated/install-scriptis
我是根据linkis官网中的构建步骤进行构建的，构建过程中无任何报错信息
I constructed according to the construction steps in the official website of linkis, and no error information was reported during the construction process

**Comment by casionone** [comment]
> > > > “在scriptis页面中，无法输入任何语句” 浏览器调试模式下的任何错误消息？ ![图像](https://private-user-images.githubusercontent.com/7869972/291023529-65f9ee17-e812-4516-a491-9b8e7e0b879c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODM4NTIsIm5iZiI6MTcwMjk4MzU1MiwicGF0aCI6Ii83ODY5OTcyLzI5MTAyMzUyOS02NWY5ZWUxNy1lODEyLTQ1MTYtYTQ5MS05YjhlN2UwYjg3OWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTA1OTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdkMjhkNzYwNWNiODcyNDRkNTYyOGM1MGQ4MGY2OTg2ZGQ3MGMxODg3ZTc0YWIxZDYxMzgwOWU4YWI5NGNkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.96wJrRISUVD8Qt-Nk48tUU_pfGLCcKjADOMRX-mYOC0)
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/44761036/291573686-85344fd1-ae47-4163-bbfc-e93ab47f9dbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjQ0MDMsIm5iZiI6MTcwMzEyNDEwMywicGF0aCI6Ii80NDc2MTAzNi8yOTE1NzM2ODYtODUzNDRmZDEtYWU0Ny00MTYzLWJiZmMtZTkzYWI0N2Y5ZGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyMDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjI0MTBmZGFmYmM2YjU3YTU3MGY0ZTFjNmJmYTA0ODY2OGFmZThkYTBiMGFkM2RjODMzODY2YjZmMDQwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ky27OULN4pvOld1SjgoZWIEbfzURfpjP9Uhu55dfV1Q)
> > > 这个是我在打开scriptis页面时的报错截图，在打开jdbc的文件到编辑页面并没有任何输出和报错
> > 
> > 
> > can you give the detail process about you build scriptis web resource
> 
> https://linkis.apache.org/zh-CN/docs/latest/deployment/integrated/install-scriptis 我是根据linkis官网中的构建步骤进行构建的，构建过程中无任何报错信息，使用的是dss1.1.2源码构建的 I constructed according to the construction steps in the official website of linkis, and no error information was reported during the construction process. It is built using dss1.1.2 source code



> > > > “在scriptis页面中，无法输入任何语句” 浏览器调试模式下的任何错误消息？ ![图像](https://private-user-images.githubusercontent.com/7869972/291023529-65f9ee17-e812-4516-a491-9b8e7e0b879c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODM4NTIsIm5iZiI6MTcwMjk4MzU1MiwicGF0aCI6Ii83ODY5OTcyLzI5MTAyMzUyOS02NWY5ZWUxNy1lODEyLTQ1MTYtYTQ5MS05YjhlN2UwYjg3OWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTA1OTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdkMjhkNzYwNWNiODcyNDRkNTYyOGM1MGQ4MGY2OTg2ZGQ3MGMxODg3ZTc0YWIxZDYxMzgwOWU4YWI5NGNkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.96wJrRISUVD8Qt-Nk48tUU_pfGLCcKjADOMRX-mYOC0)
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/44761036/291573686-85344fd1-ae47-4163-bbfc-e93ab47f9dbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjQ0MDMsIm5iZiI6MTcwMzEyNDEwMywicGF0aCI6Ii80NDc2MTAzNi8yOTE1NzM2ODYtODUzNDRmZDEtYWU0Ny00MTYzLWJiZmMtZTkzYWI0N2Y5ZGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyMDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjI0MTBmZGFmYmM2YjU3YTU3MGY0ZTFjNmJmYTA0ODY2OGFmZThkYTBiMGFkM2RjODMzODY2YjZmMDQwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ky27OULN4pvOld1SjgoZWIEbfzURfpjP9Uhu55dfV1Q)
> > > 这个是我在打开scriptis页面时的报错截图，在打开jdbc的文件到编辑页面并没有任何输出和报错
> > 
> > 
> > can you give the detail process about you build scriptis web resource
> 
> https://linkis.apache.org/zh-CN/docs/latest/deployment/integrated/install-scriptis 我是根据linkis官网中的构建步骤进行构建的，构建过程中无任何报错信息，使用的是dss1.1.2源码构建的 I constructed according to the construction steps in the official website of linkis, and no error information was reported during the construction process. It is built using dss1.1.2 source code

We can add WeChat friends. My WeChat ID is: casionen. We will further confirm whether this issue is caused by the incompatibility of the new dss version.

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量

**Comment by ly-yhq** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
