### ISSUE TITLE
[Question]   dss1.12 + streamis + linkins1.5   streamis停止flink任务 , 但是yarn里面的任务没停止

### ISSUE THREAD

**Issue by 18308996929** [apache/linkis#5063]
### Before asking

- [ ] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Describe your questions

  我看源码是因为 /XXXXX/036e3c5c-8038-4633-a5e9-495a7e7f7133/logs/yarnApp。  yarnApp文件不存在导致,。

   具体是否和yarnApp文件有关, 就不确定了！  大佬,  帮忙指点下  

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/linkis/files/9219529/yarn-error.log)

**Comment by GLeXios** [comment]
你好，这个问题在后续版本修复了，可以尝试升级到streamis 0.3.0 ，linkis升级到 1.4.0以上
