### ISSUE TITLE
[Question] 工作流 sqoop节点执行失败,  其实后台数据已经同步。  如果进入sqoop节点执行也是成功

### ISSUE THREAD

**Issue by 18308996929** [apache/linkis#5070]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

linkis1.4.0

### Describe your questions

![3b4515875f91716c8a2203686d48abb](https://github.com/apache/linkis/assets/51193865/5dc62c82-1e0d-4e8a-b183-50cc32acd880)

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/linkis/files/9219529/yarn-error.log)

**Comment by peacewong** [comment]
You need to go to the linkis management console to check whether the task is successful. If it fails, you need to check the log of the task.
