### ISSUE TITLE
[Question] linkis1.3.0-linkis.engineplugin.jdbc: statement is closed

### ISSUE THREAD

**Issue by livi12138** [apache/linkis#5071]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.0
- Environment name and version:
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Describe your questions

当我使用linkis.engineplugin.jdbc 时，会出现 statement is closed 报错，请问是使用DruidDataSource设置了RemoveAbandonedTimeout的问题吗？该如何改进呢，将时间延长设置后，随着引擎的使用还是会出现这个报错
When I use linkis.engineplugin.jdbc, I get the error statement is closed. Is it because of the RemoveAbandonedTimeout setting when using DruidDataSource? How to improve it?When the time extension setting is set, this error still appears with the use of the engine.

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

````log

execute failed, 21304, Task is Failed, errorMsg: Statement is closed

````

**Comment by casionone** [comment]
Can add  wechat friend  my wxid:casionen

**Comment by peacewong** [comment]
Fix by this commit：https://github.com/apache/linkis/pull/5007/commits/87b29fe94e58714838e6f67284579128109ef784
