### ISSUE TITLE
[Bug] bin tar.gz has akka licenses but no akka libs

### ISSUE THREAD

**Issue by pjfanning** [apache/linkis#5084]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-dist

### Steps to reproduce

* Download binary distribution from https://linkis.apache.org/download/main/ (v1.5.0)
* untar

### Expected behavior

The licenses dir has LICENSE-akka-stream_2.11.txt (plus 3 more similar files) but I can't find any akka libs or code.

Why do you have Akka licenses? Akka 2.5 was open source but more recent relaeses as Category X licensed.

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Okay, Linkis does not use Akka, let’s remove it. I will submit RP to remove it

**Comment by peacewong** [comment]
Fix by #5103
