### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yusp998** [apache/linkis#5118]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### Steps to reproduce

1.linkis-storage里面解析邮件内容报空指针异常，注释异常代码，如下图为注释代码和日志
![1715944816037](https://github.com/apache/linkis/assets/126861196/47348deb-180a-4194-bd2f-0a7ac780784f)
![e04dae2bdb666e993a535b2b386d7e1](https://github.com/apache/linkis/assets/126861196/9d311247-db82-4ca3-a6ae-569f0a0016d8)

2.发现日志中疑点  Get Result Set By Path:/storage/work/tmp/linkis/hadoop/linkis/2024-05-17/175102/nodeexecution/9823/_0.dolphin fsPath getFsType hdfs，这里似乎应该得到dolphin内容，如下图
![1715945071157](https://github.com/apache/linkis/assets/126861196/db582c08-c756-464d-93e4-1da0fe072144)

3.在解析邮件内容，测试了邮件内容如下dolphin00000000010000000004NULL0000000011hello world，但是Dolphin.java中解析过程中发现解析方式和邮件内容不匹配，如下图
![1715945298041](https://github.com/apache/linkis/assets/126861196/2854f974-8b7c-4409-8478-c2a88f01a853)

希望得到技术支持，目前无法使用发送邮件的组件

### Expected behavior

希望得到技术支持，目前无法使用发送邮件的组件

### Your environment

- Linkis version used: 1.4.0
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
1.5. 0 has fixed the bug, 1.4. 0 can update the merge this commit #4996
