### ISSUE TITLE
[Question] 下载源码后，执行mvn -N install成功，但是执行mvn clean install 报错

### ISSUE THREAD

**Issue by HXB-123** [apache/linkis#5193]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - hdp-3.3.5
    - hive-4.0.1
    - spark-3.5.3
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Describe your questions

[INFO] linkis-entrance .................................... SUCCESS [ 22.830 s]
[INFO] linkis-cli ......................................... SUCCESS [  3.102 s]
[INFO] linkis-jdbc-driver ................................. SUCCESS [ 11.935 s]
[INFO] linkis-computation-governance ...................... SUCCESS [  0.130 s]
[INFO] linkis-engineplugin-hive ........................... SUCCESS [ 19.666 s]
[INFO] linkis-engineplugin-spark .......................... FAILURE [ 34.137 s]
[INFO] linkis-engineplugin-python ......................... SKIPPED
[INFO] linkis-engineplugin-openlookeng .................... SKIPPED
[INFO] linkis-engineplugin-io_file ........................ SKIPPED
[INFO] linkis-engineplugin-shell .......................... SKIPPED
[INFO] linkis-engineplugin-pipeline ....................... SKIPPED
[INFO] linkis-engineplugin-jdbc ........................... SKIPPED
[INFO] flink-shims ........................................ SKIPPED
[INFO] flink-shims-1.12.2 ................................. SKIPPED
[INFO] flink-shims-1.16.2 ................................. SKIPPED
[INFO] linkis-engineconn-plugin-flink ..................... SKIPPED
[INFO] linkis-engineconn-plugin-flink-module .............. SKIPPED
[INFO] linkis-engineplugin-sqoop .......................... SKIPPED
[INFO] linkis-engineplugin-presto ......................... SKIPPED
[INFO] linkis-engineplugin-trino .......................... SKIPPED
[INFO] linkis-engineplugin-elasticsearch .................. SKIPPED
[INFO] linkis-engineplugin-seatunnel ...................... SKIPPED
[INFO] hbase-shims-2.5.3 .................................. SKIPPED
[INFO] linkis-engineconn-plugin-hbase ..................... SKIPPED
[INFO] hbase-shims-1.2.0 .................................. SKIPPED
[INFO] hbase-shims-1.4.3 .................................. SKIPPED
[INFO] hbase-shims-2.2.6 .................................. SKIPPED
[INFO] linkis-engineconn-plugin-hbase-module .............. SKIPPED
[INFO] linkis-engineplugin-nebula ......................... SKIPPED
[INFO] linkis-engineplugin-doris .......................... SKIPPED
[INFO] linkis-engineplugin-repl ........................... SKIPPED
[INFO] linkis-engineconn-plugins .......................... SKIPPED
[INFO] linkis-et-monitor .................................. SKIPPED
[INFO] linkis-extensions .................................. SKIPPED
[INFO] linkis-dist ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:58 min
[INFO] Finished at: 2024-10-26T14:10:37+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project linkis-engineplugin-spark:
[ERROR]
[ERROR] Please refer to D:\linkis-master\linkis-engineconn-plugins\spark\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Eclipse Adoptium\jdk-8.0.412.8-hotspot\jre\bin\java" -javaagent:C:\\Users\\hw0017806\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.8\\org.jacoco.agent-0.8.8-runtime.jar=destfile=D:\\link
is-master\\linkis-engineconn-plugins\\spark\\target\\jacoco.exec -jar C:\Users\hw0017806\AppData\Local\Temp\surefire3491833478737061882\surefirebooter-20241026141026577_470.jar C:\Users\hw0017806\AppData\Local\Temp\surefire3491833478737061882 2024-10-26T14-03-53_008-jvmRun1 surefire-20241026141026577_465tmp surefire_36-20241026141026577_468tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] org.apache.linkis.engineplugin.spark.executor.TestSparkSqlExecutor
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Eclipse Adoptium\jdk-8.0.412.8-hotspot\jre\bin\java" -javaagent:C:\\Users\\hw0017806\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.8\\org.jacoco.agent-0.8.8-runtime.jar=destfile=D:\\link
is-master\\linkis-engineconn-plugins\\spark\\target\\jacoco.exec -jar C:\Users\hw0017806\AppData\Local\Temp\surefire3491833478737061882\surefirebooter-20241026141026577_471.jar C:\Users\hw0017806\AppData\Local\Temp\surefire3491833478737061882 2024-10-26T14-03-53_008-jvmRun3 surefire-20241026141026577_464tmp surefire_35-20241026141026577_467tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] org.apache.linkis.engineplugin.spark.cs.TestCSSparkPostExecutionHook
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Eclipse Adoptium\jdk-8.0.412.8-hotspot\jre\bin\java" -javaagent:C:\\Users\\hw0017806\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.8\\org.jacoco.agent-0.8.8-runtime.jar=destfile=D:\\link
is-master\\linkis-engineconn-plugins\\spark\\target\\jacoco.exec -jar C:\Users\hw0017806\AppData\Local\Temp\surefire3491833478737061882\surefirebooter-20241026141026577_470.jar C:\Users\hw0017806\AppData\Local\Temp\surefire3491833478737061882 2024-10-26T14-03-53_008-jvmRun1 surefire-20241026141026577_465tmp surefire_36-20241026141026577_468tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] org.apache.linkis.engineplugin.spark.executor.TestSparkSqlExecutor
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Eclipse Adoptium\jdk-8.0.412.8-hotspot\jre\bin\java" -javaagent:C:\\Users\\hw0017806\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.8\\org.jacoco.agent-0.8.8-runtime.jar=destfile=D:\\link
is-master\\linkis-engineconn-plugins\\spark\\target\\jacoco.exec -jar C:\Users\hw0017806\AppData\Local\Temp\surefire3491833478737061882\surefirebooter-20241026141026577_471.jar C:\Users\hw0017806\AppData\Local\Temp\surefire3491833478737061882 2024-10-26T14-03-53_008-jvmRun3 surefire-20241026141026577_464tmp surefire_35-20241026141026577_467tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] org.apache.linkis.engineplugin.spark.cs.TestCSSparkPostExecutionHook
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:513)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:397)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:326)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:269)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1334)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1167)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:931)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
[ERROR]         at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Eclipse Adoptium\jdk-8.0.412.8-hotspot\jre\bin\java" -javaagent:C:\\Users\\hw0017806\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.8\\org.jacoco.agent-0.8.8-runtime.jar=destfile=D:\\linkis-master\\linkis-engineconn-plugins\\spark\\target\\jacoco.exec -jar C:\Users\hw0017806\AppData\Local\Temp\surefire3491833478737061882\surefirebooter-20241026141026577_471.jar C:\Users\hw0017806\AppData\Local\Temp\surefire3491833478737061882 2024-10-26T14-03-53_008-jvmRun3 surefire-20241026141026577_464tmp surefire_35-20241026141026577_467tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] org.apache.linkis.engineplugin.spark.cs.TestCSSparkPostExecutionHook
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:714)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.lambda$runSuitesForkOnceMultiple$3(ForkStarter.java:388)
[ERROR]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[ERROR]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[ERROR]         at java.lang.Thread.run(Thread.java:750)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :linkis-engineplugin-spark

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/linkis/files/9219529/yarn-error.log)

**Comment by peacewong** [comment]
can add params: -DskipTests
