### ISSUE TITLE
[Feature][spark] spark引擎增加对sparkmeasure的支持

### ISSUE THREAD

**Issue by sjgllgh** [apache/linkis#5200]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/linkis/issues) and found no similar feature requirement.

### Problem Description

1.  spark引擎增加对sparkmeasure的支持，便于对spark任务进行分析

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Good features
